import { romajiToHiragana } from "@/lib/speech";

export const recognitionVariantsByRomaji: Record<string, string[]> = {
  abunai: ["危ない", "危険"],
  ageru: ["あげる", "上げる", "挙げる"],
  ai: ["愛"],
  aishiteru: ["愛してる", "愛している"],
  aitai: ["会いたい", "逢いたい"],
  akarui: ["明るい"],
  amari: ["あまり", "余り"],
  ame: ["雨"],
  ani: ["兄"],
  anshin: ["安心"],
  anzen: ["安全"],
  apuri: ["アプリ"],
  arigatou: ["ありがとう", "有難う"],
  aruku: ["歩く"],
  asa: ["朝"],
  asobu: ["遊ぶ"],
  ashita: ["明日"],
  ato: ["後", "あと"],
  atsui: ["暑い", "熱い"],
  au: ["会う", "逢う"],
  basu: ["バス"],
  benkyou: ["勉強"],
  benri: ["便利"],
  byouin: ["病院"],
  chikaku: ["近く"],
  chikara: ["力"],
  chiisai: ["小さい"],
  daijoubu: ["大丈夫"],
  dame: ["だめ", "駄目"],
  dare: ["誰"],
  deeto: ["デート"],
  dekiru: ["出来る", "できる"],
  dekinai: ["出来ない", "できない"],
  denchi: ["電池"],
  densha: ["電車"],
  denwa: ["電話"],
  deru: ["出る"],
  dou: ["どう"],
  doa: ["ドア"],
  dochira: ["どちら"],
  doko: ["どこ", "何処"],
  donna: ["どんな"],
  "donna hito": ["どんな人"],
  e: ["絵"],
  eiga: ["映画"],
  eki: ["駅"],
  erabu: ["選ぶ"],
  fuku: ["服"],
  furui: ["古い"],
  gakkou: ["学校"],
  ganbatte: ["頑張って", "がんばって"],
  genjitsu: ["現実"],
  genkin: ["現金"],
  gomen: ["ごめん", "御免"],
  gohan: ["ご飯", "御飯"],
  hai: ["はい"],
  hairu: ["入る"],
  hajimaru: ["始まる"],
  hajime: ["始め", "初め"],
  hana: ["花", "鼻"],
  hanashi: ["話"],
  hanasu: ["話す"],
  hashiru: ["走る"],
  hayai: ["早い", "速い"],
  hen: ["変"],
  heya: ["部屋"],
  hi: ["火", "日"],
  hikouki: ["飛行機"],
  hima: ["暇"],
  himitsu: ["秘密"],
  hiru: ["昼"],
  hito: ["人"],
  hon: ["本"],
  hontou: ["本当"],
  hoshi: ["星"],
  ie: ["家"],
  iie: ["いいえ"],
  ii: ["いい", "良い"],
  iku: ["行く"],
  ikura: ["いくら", "幾ら"],
  ima: ["今"],
  imi: ["意味"],
  imouto: ["妹"],
  inu: ["犬"],
  isu: ["椅子", "いす"],
  itai: ["痛い"],
  itsu: ["いつ"],
  itsumo: ["いつも"],
  iya: ["いや", "嫌"],
  jikan: ["時間"],
  jiko: ["事故"],
  jitensha: ["自転車"],
  jiyuu: ["自由"],
  jouzu: ["上手"],
  juuden: ["充電"],
  kaado: ["カード"],
  kaeru: ["帰る", "返る"],
  kagi: ["鍵"],
  kaisha: ["会社"],
  kaigi: ["会議"],
  kakkoii: ["かっこいい"],
  kamera: ["カメラ"],
  kaban: ["鞄", "かばん"],
  kantan: ["簡単"],
  karui: ["軽い"],
  kasa: ["傘"],
  kaze: ["風"],
  kazoku: ["家族"],
  kau: ["買う"],
  kaette: ["帰って"],
  keiken: ["経験"],
  keisatsu: ["警察"],
  kesa: ["今朝"],
  ki: ["木"],
  kibishii: ["厳しい"],
  kibou: ["希望"],
  kiku: ["聞く", "聴く"],
  kimaru: ["決まる"],
  kimochi: ["気持ち"],
  kinou: ["昨日"],
  kirai: ["嫌い"],
  kirei: ["綺麗", "きれい"],
  kite: ["来て"],
  koi: ["恋"],
  koibito: ["恋人"],
  koe: ["声"],
  kokoro: ["心"],
  kodomo: ["子供", "こども"],
  komaru: ["困る"],
  konban: ["今晩"],
  konnichiwa: ["こんにちは", "今日は"],
  kondo: ["今度"],
  kore: ["これ"],
  "kore wa nan desu ka": ["これは何ですか", "これはなんですか"],
  kotae: ["答え"],
  kotaeru: ["答える"],
  kowai: ["怖い"],
  kuni: ["国"],
  kurai: ["暗い"],
  kureru: ["くれる"],
  kuru: ["来る"],
  kuruma: ["車"],
  kusuri: ["薬"],
  kutsu: ["靴"],
  kyuujitsu: ["休日"],
  kyou: ["今日"],
  machi: ["町", "街"],
  mado: ["窓"],
  mada: ["まだ"],
  mae: ["前"],
  majime: ["真面目"],
  mate: ["待て", "待って"],
  matsu: ["待つ"],
  mayoi: ["迷い"],
  "me ru": ["メール"],
  messeeji: ["メッセージ"],
  michi: ["道"],
  mijikai: ["短い"],
  minna: ["みんな", "皆"],
  mirai: ["未来"],
  miru: ["見る"],
  mise: ["店"],
  mizu: ["水"],
  mochiron: ["もちろん", "勿論"],
  mondai: ["問題"],
  morau: ["もらう", "貰う"],
  mou: ["もう"],
  mura: ["村"],
  muzukashii: ["難しい"],
  na: ["な"],
  nagai: ["長い"],
  namae: ["名前"],
  naku: ["泣く"],
  nani: ["何"],
  narau: ["習う"],
  nareru: ["慣れる"],
  naze: ["なぜ", "何故"],
  neko: ["猫"],
  nemui: ["眠い"],
  nenrei: ["年齢"],
  neru: ["寝る"],
  nigiyaka: ["賑やか"],
  nomu: ["飲む"],
  noru: ["乗る"],
  ocha: ["お茶"],
  odoru: ["踊る"],
  ohayou: ["おはよう", "お早う"],
  okaasan: ["お母さん", "母"],
  okane: ["お金"],
  okiru: ["起きる"],
  okoru: ["怒る"],
  omatsuri: ["お祭り", "祭り"],
  omoi: ["重い", "思い"],
  onaka: ["お腹", "腹"],
  onna: ["女"],
  ongaku: ["音楽"],
  onegai: ["お願い"],
  oriru: ["降りる"],
  oshieru: ["教える"],
  osoi: ["遅い"],
  oto: ["音"],
  otoko: ["男"],
  otousan: ["お父さん", "父"],
  paatii: ["パーティー"],
  pan: ["パン"],
  pasokon: ["パソコン"],
  rajio: ["ラジオ"],
  raishuu: ["来週"],
  receipto: ["レシート"],
  renshuu: ["練習"],
  resutoran: ["レストラン"],
  ryokou: ["旅行"],
  sabishii: ["寂しい"],
  saigo: ["最後"],
  sakana: ["魚"],
  samui: ["寒い"],
  sekai: ["世界"],
  seikou: ["成功"],
  sensei: ["先生"],
  shashin: ["写真"],
  shiawase: ["幸せ"],
  shigoto: ["仕事"],
  shinjiru: ["信じる"],
  shinsetsu: ["親切"],
  shinpai: ["心配"],
  shippai: ["失敗"],
  shitsumon: ["質問"],
  shizuka: ["静か"],
  shuumatsu: ["週末"],
  sora: ["空"],
  sugoi: ["すごい", "凄い"],
  suki: ["好き"],
  sukoshi: ["少し"],
  sumimasen: ["すみません", "済みません"],
  suru: ["する"],
  suteki: ["素敵"],
  taberu: ["食べる"],
  tabun: ["多分"],
  taihen: ["大変"],
  taisetsu: ["大切"],
  taiyou: ["太陽"],
  takai: ["高い"],
  takusan: ["たくさん", "沢山"],
  tanjoubi: ["誕生日"],
  tasukaru: ["助かる"],
  tasukete: ["助けて"],
  tazuneru: ["尋ねる"],
  terebi: ["テレビ"],
  toire: ["トイレ"],
  tokidoki: ["時々"],
  toki: ["時"],
  tokubetsu: ["特別"],
  tomodachi: ["友達"],
  tooi: ["遠い"],
  tori: ["鳥"],
  tsuchi: ["土"],
  tsuki: ["月"],
  tsukareta: ["疲れた"],
  tsukau: ["使う"],
  tsukue: ["机"],
  tsuzuku: ["続く"],
  uma: ["馬"],
  umi: ["海"],
  urusai: ["うるさい"],
  usagi: ["兎", "うさぎ"],
  uta: ["歌"],
  utsukushii: ["美しい"],
  wakaranai: ["分からない", "わからない"],
  wakareru: ["別れる"],
  wakaru: ["分かる", "わかる"],
  warau: ["笑う"],
  watashi: ["私", "わたし"],
  "watashi wa david desu": ["私はDavidです", "わたしはDavidです", "私はデイビッドです"],
  yama: ["山"],
  yasashii: ["優しい"],
  yasui: ["安い"],
  yasumi: ["休み"],
  yokatta: ["良かった"],
  yomu: ["読む"],
  yorokobu: ["喜ぶ"],
  yoru: ["夜"],
  yuuki: ["勇気"],
  yume: ["夢"],
  zenbu: ["全部"],
  zenzen: ["全然"],
  zettai: ["絶対"],
};

function normalizeRomajiKey(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function unique(values: string[]): string[] {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)));
}

export function getRecognitionVariantEntries() {
  return Object.entries(recognitionVariantsByRomaji).flatMap(([romaji, variants]) =>
    variants.map((variant) => ({
      romaji,
      variant,
    })),
  );
}

export function getJapaneseRecognitionVariants(
  expectedRomaji: string,
  expectedKana?: string,
  extraVariants: string[] = [],
): string[] {
  const normalizedRomaji = normalizeRomajiKey(expectedRomaji);
  const generatedKana = romajiToHiragana(normalizedRomaji);

  return unique([
    generatedKana,
    expectedKana ?? "",
    ...(recognitionVariantsByRomaji[normalizedRomaji] ?? []),
    ...extraVariants,
  ]);
}
