import { createInitialProgress } from "@/lib/srs";
import type { CardProgress, VocabularyCard } from "@/types/card";

const createdAt = "2026-01-01T00:00:00.000Z";
const initialDueAt = new Date("2024-01-01T00:00:00.000Z");

export const mockCards: VocabularyCard[] = [
  {
    id: "card-mizu",
    type: "word",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "みず",
    learningReading: "mizu",
    supportText: "agua",
    japaneseRomaji: "mizu",
    japaneseKana: "みず",
    spanish: "agua",
    category: "supervivencia",
    createdAt,
  },
  {
    id: "card-inu",
    type: "word",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "いぬ",
    learningReading: "inu",
    supportText: "perro",
    japaneseRomaji: "inu",
    japaneseKana: "いぬ",
    spanish: "perro",
    category: "animales",
    createdAt,
  },
  {
    id: "card-neko",
    type: "word",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "ねこ",
    learningReading: "neko",
    supportText: "gato",
    japaneseRomaji: "neko",
    japaneseKana: "ねこ",
    spanish: "gato",
    category: "animales",
    createdAt,
  },
  {
    id: "card-arigatou",
    type: "word",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "ありがとう",
    learningReading: "arigatou",
    supportText: "gracias",
    japaneseRomaji: "arigatou",
    japaneseKana: "ありがとう",
    spanish: "gracias",
    category: "saludos",
    createdAt,
  },
  {
    id: "card-sumimasen",
    type: "word",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "すみません",
    learningReading: "sumimasen",
    supportText: "disculpa / perdón",
    japaneseRomaji: "sumimasen",
    japaneseKana: "すみません",
    spanish: "disculpa / perdón",
    category: "supervivencia",
    createdAt,
  },
  {
    id: "card-konnichiwa",
    type: "word",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "こんにちは",
    learningReading: "konnichiwa",
    supportText: "hola / buenas tardes",
    japaneseRomaji: "konnichiwa",
    japaneseKana: "こんにちは",
    spanish: "hola / buenas tardes",
    category: "saludos",
    createdAt,
  },
  {
    id: "card-ohayou",
    type: "word",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "おはよう",
    learningReading: "ohayou",
    supportText: "buenos días",
    japaneseRomaji: "ohayou",
    japaneseKana: "おはよう",
    spanish: "buenos días",
    category: "saludos",
    createdAt,
  },
  {
    id: "card-watashi-wa-david-desu",
    type: "phrase",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "わたしはDavidです",
    learningReading: "watashi wa David desu",
    supportText: "soy David",
    japaneseRomaji: "watashi wa David desu",
    japaneseKana: "わたしはDavidです",
    spanish: "soy David",
    category: "presentación",
    createdAt,
  },
  {
    id: "card-colombia-kara-kimashita",
    type: "phrase",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "Colombiaからきました",
    learningReading: "Colombia kara kimashita",
    supportText: "vengo de Colombia",
    japaneseRomaji: "Colombia kara kimashita",
    japaneseKana: "Colombiaからきました",
    spanish: "vengo de Colombia",
    category: "presentación",
    createdAt,
  },
  {
    id: "card-kore-wa-nan-desu-ka",
    type: "phrase",
    isStarter: true,
    learningMode: "ja_es",
    learningLanguage: "ja",
    supportLanguage: "es",
    learningText: "これはなんですか",
    learningReading: "kore wa nan desu ka",
    supportText: "¿qué es esto?",
    japaneseRomaji: "kore wa nan desu ka",
    japaneseKana: "これはなんですか",
    spanish: "¿qué es esto?",
    category: "preguntas comunes",
    createdAt,
  },
  {
    id: "card-ko-agua",
    type: "word",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "agua",
    supportText: "물",
    supportReading: "mul",
    spanish: "물",
    category: "생존",
    createdAt,
  },
  {
    id: "card-ko-perro",
    type: "word",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "perro",
    supportText: "개",
    supportReading: "gae",
    spanish: "개",
    category: "동물",
    createdAt,
  },
  {
    id: "card-ko-gato",
    type: "word",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "gato",
    supportText: "고양이",
    supportReading: "goyangi",
    spanish: "고양이",
    category: "동물",
    createdAt,
  },
  {
    id: "card-ko-gracias",
    type: "word",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "gracias",
    supportText: "감사합니다",
    supportReading: "gamsahamnida",
    spanish: "감사합니다",
    category: "인사",
    createdAt,
  },
  {
    id: "card-ko-perdon",
    type: "word",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "disculpa / perdón",
    supportText: "실례합니다 / 죄송합니다",
    supportReading: "sillyehamnida / joesonghamnida",
    spanish: "실례합니다 / 죄송합니다",
    category: "생존",
    createdAt,
  },
  {
    id: "card-ko-hola",
    type: "word",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "hola / buenas tardes",
    supportText: "안녕하세요",
    supportReading: "annyeonghaseyo",
    spanish: "안녕하세요",
    category: "인사",
    createdAt,
  },
  {
    id: "card-ko-buenos-dias",
    type: "word",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "buenos días",
    supportText: "좋은 아침이에요",
    supportReading: "joeun achimieyo",
    spanish: "좋은 아침이에요",
    category: "인사",
    createdAt,
  },
  {
    id: "card-ko-soy-david",
    type: "phrase",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "soy David",
    supportText: "저는 David입니다",
    supportReading: "jeoneun David imnida",
    spanish: "저는 David입니다",
    category: "소개",
    createdAt,
  },
  {
    id: "card-ko-vengo-de-colombia",
    type: "phrase",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "vengo de Colombia",
    supportText: "콜롬비아에서 왔어요",
    supportReading: "kolombia-eseo wasseoyo",
    spanish: "콜롬비아에서 왔어요",
    category: "소개",
    createdAt,
  },
  {
    id: "card-ko-que-es-esto",
    type: "phrase",
    isStarter: true,
    learningMode: "ko_es",
    learningLanguage: "es",
    supportLanguage: "ko",
    learningText: "¿qué es esto?",
    supportText: "이것은 무엇인가요?",
    supportReading: "igeoseun mueosingayo",
    spanish: "이것은 무엇인가요?",
    category: "자주 쓰는 질문",
    createdAt,
  },
];

export const mockProgress: CardProgress[] = mockCards.map((card) =>
  createInitialProgress(card.id, undefined, initialDueAt),
);
