export interface StarterVocabularyEntry {
  number: number;
  block: string;
  category: string;
  categoryKo: string;
  romaji: string;
  spanish: string;
  korean: string;
  koreanReading: string;
  imageCode: string;
}

export const TWEMOJI_BASE_URL =
  "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg";

export const starterVocabularyEntries = [
  { number: 1, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "watashi", spanish: "yo", korean: "나", koreanReading: "na", imageCode: "1f464" },
  { number: 2, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "namae", spanish: "nombre", korean: "이름", koreanReading: "ireum", imageCode: "1f4db" },
  { number: 3, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "nenrei", spanish: "edad", korean: "나이", koreanReading: "nai", imageCode: "1f382" },
  { number: 4, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "hito", spanish: "persona", korean: "사람", koreanReading: "saram", imageCode: "1f9d1" },
  { number: 5, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "otoko", spanish: "hombre", korean: "남자", koreanReading: "namja", imageCode: "1f468" },
  { number: 6, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "onna", spanish: "mujer", korean: "여자", koreanReading: "yeoja", imageCode: "1f469" },
  { number: 7, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "kodomo", spanish: "niño", korean: "아이", koreanReading: "ai", imageCode: "1f9d2" },
  { number: 8, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "tomodachi", spanish: "amigo", korean: "친구", koreanReading: "chingu", imageCode: "1f91d" },
  { number: 9, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "kazoku", spanish: "familia", korean: "가족", koreanReading: "gajok", imageCode: "1f46a" },
  { number: 10, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "otousan", spanish: "padre", korean: "아버지", koreanReading: "abeoji", imageCode: "1f468" },
  { number: 11, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "okaasan", spanish: "madre", korean: "어머니", koreanReading: "eomeoni", imageCode: "1f469" },
  { number: 12, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "ani", spanish: "hermano mayor", korean: "형 또는 오빠", koreanReading: "hyeong ttoneun oppa", imageCode: "1f466" },
  { number: 13, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "imouto", spanish: "hermana menor", korean: "여동생", koreanReading: "yeodongsaeng", imageCode: "1f467" },
  { number: 14, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "sensei", spanish: "profesor", korean: "선생님", koreanReading: "seonsaengnim", imageCode: "1f3eb" },
  { number: 15, block: "A", category: "Identidad personal", categoryKo: "개인 신원", romaji: "koibito", spanish: "pareja", korean: "연인", koreanReading: "yeonin", imageCode: "1f491" },
  { number: 16, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "hai", spanish: "sí", korean: "네", koreanReading: "ne", imageCode: "2705" },
  { number: 17, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "iie", spanish: "no", korean: "아니요", koreanReading: "aniyo", imageCode: "274c" },
  { number: 18, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "daijoubu", spanish: "está bien", korean: "괜찮아요", koreanReading: "gwaenchanayo", imageCode: "1f197" },
  { number: 19, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "dame", spanish: "no se puede", korean: "안 돼요", koreanReading: "an dwaeyo", imageCode: "1f6ab" },
  { number: 20, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "ii", spanish: "bien", korean: "좋아요", koreanReading: "joayo", imageCode: "1f44d" },
  { number: 21, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "sumimasen", spanish: "disculpa", korean: "실례합니다", koreanReading: "sillyehamnida", imageCode: "1f64f" },
  { number: 22, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "gomen", spanish: "perdón", korean: "미안해요", koreanReading: "mianhaeyo", imageCode: "1f64f" },
  { number: 23, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "onegai", spanish: "por favor", korean: "부탁해요", koreanReading: "butakhaeyo", imageCode: "1f64f" },
  { number: 24, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "hontou", spanish: "verdad", korean: "진짜", koreanReading: "jinjja", imageCode: "1f4af" },
  { number: 25, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "mochiron", spanish: "claro", korean: "물론이죠", koreanReading: "mullonijyo", imageCode: "1f44c" },
  { number: 26, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "tabun", spanish: "tal vez", korean: "아마", koreanReading: "ama", imageCode: "1f914" },
  { number: 27, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "yokatta", spanish: "qué bueno", korean: "잘됐네요", koreanReading: "jal dwaetneyo", imageCode: "1f60a" },
  { number: 28, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "iya", spanish: "no quiero", korean: "싫어요", koreanReading: "sireoyo", imageCode: "1f645" },
  { number: 29, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "mate", spanish: "espera", korean: "기다려요", koreanReading: "gidaryeoyo", imageCode: "23f3" },
  { number: 30, block: "B", category: "Respuestas inmediatas", categoryKo: "즉각 응답", romaji: "kite", spanish: "ven", korean: "와요", koreanReading: "wayo", imageCode: "1f44b" },
  { number: 31, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "wakaru", spanish: "entender", korean: "이해하다", koreanReading: "ihaehada", imageCode: "1f4a1" },
  { number: 32, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "wakaranai", spanish: "no entender", korean: "이해하지 못하다", koreanReading: "ihaehaji mothada", imageCode: "2753" },
  { number: 33, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "hanasu", spanish: "hablar", korean: "말하다", koreanReading: "malhada", imageCode: "1f5e3" },
  { number: 34, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "kiku", spanish: "escuchar / preguntar", korean: "듣다 / 묻다", koreanReading: "deutda / mutda", imageCode: "1f442" },
  { number: 35, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "koe", spanish: "voz", korean: "목소리", koreanReading: "moksori", imageCode: "1f3a4" },
  { number: 36, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "oto", spanish: "sonido", korean: "소리", koreanReading: "sori", imageCode: "1f50a" },
  { number: 37, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "hanashi", spanish: "conversación", korean: "대화", koreanReading: "daehwa", imageCode: "1f4ac" },
  { number: 38, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "shitsumon", spanish: "pregunta", korean: "질문", koreanReading: "jilmun", imageCode: "2753" },
  { number: 39, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "kotae", spanish: "respuesta", korean: "대답", koreanReading: "daedap", imageCode: "2705" },
  { number: 40, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "imi", spanish: "significado", korean: "의미", koreanReading: "uimi", imageCode: "1f4d6" },
  { number: 41, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "denwa", spanish: "teléfono", korean: "전화", koreanReading: "jeonhwa", imageCode: "1f4de" },
  { number: 42, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "messeeji", spanish: "mensaje", korean: "메시지", koreanReading: "mesiji", imageCode: "1f4e9" },
  { number: 43, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "me-ru", spanish: "correo", korean: "이메일", koreanReading: "imeil", imageCode: "2709" },
  { number: 44, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "kotaeru", spanish: "responder", korean: "대답하다", koreanReading: "daedaphada", imageCode: "1f4e8" },
  { number: 45, block: "C", category: "Entender y hablar", categoryKo: "이해와 말하기", romaji: "tazuneru", spanish: "preguntar", korean: "묻다", koreanReading: "mutda", imageCode: "1f914" },
  { number: 46, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "iku", spanish: "ir", korean: "가다", koreanReading: "gada", imageCode: "1f6b6" },
  { number: 47, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "kuru", spanish: "venir", korean: "오다", koreanReading: "oda", imageCode: "1f44b" },
  { number: 48, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "kaeru", spanish: "volver", korean: "돌아가다", koreanReading: "doragada", imageCode: "1f504" },
  { number: 49, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "aruku", spanish: "caminar", korean: "걷다", koreanReading: "geotda", imageCode: "1f6b6" },
  { number: 50, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "hashiru", spanish: "correr", korean: "달리다", koreanReading: "dallida", imageCode: "1f3c3" },
  { number: 51, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "hairu", spanish: "entrar", korean: "들어가다", koreanReading: "deureogada", imageCode: "1f6aa" },
  { number: 52, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "deru", spanish: "salir", korean: "나가다", koreanReading: "nagada", imageCode: "1f6aa" },
  { number: 53, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "matsu", spanish: "esperar", korean: "기다리다", koreanReading: "gidarida", imageCode: "23f3" },
  { number: 54, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "suru", spanish: "hacer", korean: "하다", koreanReading: "hada", imageCode: "1f6e0" },
  { number: 55, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "dekiru", spanish: "poder hacer", korean: "할 수 있다", koreanReading: "hal su itda", imageCode: "1f4aa" },
  { number: 56, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "dekinai", spanish: "no poder", korean: "할 수 없다", koreanReading: "hal su eopda", imageCode: "1f6ab" },
  { number: 57, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "tsukau", spanish: "usar", korean: "사용하다", koreanReading: "sayonghada", imageCode: "1f527" },
  { number: 58, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "erabu", spanish: "elegir", korean: "고르다", koreanReading: "goreuda", imageCode: "2611" },
  { number: 59, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "kimaru", spanish: "decidir", korean: "결정하다", koreanReading: "gyeoljeonghada", imageCode: "1f3af" },
  { number: 60, block: "D", category: "Verbos de vida", categoryKo: "생활 동사", romaji: "ganbatte", spanish: "ánimo", korean: "힘내", koreanReading: "himnae", imageCode: "1f44a" },
  { number: 61, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "mizu", spanish: "agua", korean: "물", koreanReading: "mul", imageCode: "1f4a7" },
  { number: 62, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "gohan", spanish: "comida", korean: "음식", koreanReading: "eumsik", imageCode: "1f35a" },
  { number: 63, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "ocha", spanish: "té", korean: "차", koreanReading: "cha", imageCode: "1f375" },
  { number: 64, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "pan", spanish: "pan", korean: "빵", koreanReading: "ppang", imageCode: "1f35e" },
  { number: 65, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "onaka", spanish: "estómago", korean: "위", koreanReading: "wi", imageCode: "1f372" },
  { number: 66, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "taberu", spanish: "comer", korean: "먹다", koreanReading: "meokda", imageCode: "1f374" },
  { number: 67, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "nomu", spanish: "beber", korean: "마시다", koreanReading: "masida", imageCode: "1f964" },
  { number: 68, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "neru", spanish: "dormir", korean: "자다", koreanReading: "jada", imageCode: "1f6cc" },
  { number: 69, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "nemui", spanish: "sueño", korean: "잠", koreanReading: "jam", imageCode: "1f634" },
  { number: 70, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "tsukareta", spanish: "cansado", korean: "피곤한", koreanReading: "pigonhan", imageCode: "1f62b" },
  { number: 71, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "atsui", spanish: "calor", korean: "더위", koreanReading: "deowi", imageCode: "1f525" },
  { number: 72, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "samui", spanish: "frío", korean: "추위", koreanReading: "chuwi", imageCode: "2744" },
  { number: 73, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "byouin", spanish: "hospital", korean: "병원", koreanReading: "byeongwon", imageCode: "1f3e5" },
  { number: 74, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "kusuri", spanish: "medicina", korean: "약", koreanReading: "yak", imageCode: "1f48a" },
  { number: 75, block: "E", category: "Cuerpo y necesidades", categoryKo: "몸과 필요", romaji: "yasumi", spanish: "descanso", korean: "휴식", koreanReading: "hyusik", imageCode: "1f6cc" },
  { number: 76, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "ie", spanish: "casa", korean: "집", koreanReading: "jip", imageCode: "1f3e0" },
  { number: 77, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "eki", spanish: "estación", korean: "역", koreanReading: "yeok", imageCode: "1f689" },
  { number: 78, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "toire", spanish: "baño", korean: "화장실", koreanReading: "hwajangsil", imageCode: "1f6bd" },
  { number: 79, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "mise", spanish: "tienda", korean: "가게", koreanReading: "gage", imageCode: "1f3ea" },
  { number: 80, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "resutoran", spanish: "restaurante", korean: "식당", koreanReading: "sikdang", imageCode: "1f37d" },
  { number: 81, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "gakkou", spanish: "escuela", korean: "학교", koreanReading: "hakgyo", imageCode: "1f3eb" },
  { number: 82, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "kaisha", spanish: "empresa", korean: "회사", koreanReading: "hoesa", imageCode: "1f3e2" },
  { number: 83, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "michi", spanish: "camino", korean: "길", koreanReading: "gil", imageCode: "1f6e3" },
  { number: 84, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "machi", spanish: "ciudad", korean: "도시", koreanReading: "dosi", imageCode: "1f3d9" },
  { number: 85, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "mura", spanish: "pueblo", korean: "마을", koreanReading: "maeul", imageCode: "1f3d8" },
  { number: 86, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "kuni", spanish: "país", korean: "나라", koreanReading: "nara", imageCode: "1f5fa" },
  { number: 87, block: "F", category: "Lugares importantes", categoryKo: "중요한 장소", romaji: "sekai", spanish: "mundo", korean: "세계", koreanReading: "segye", imageCode: "1f30d" },
  { number: 88, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "okane", spanish: "dinero", korean: "돈", koreanReading: "don", imageCode: "1f4b0" },
  { number: 89, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "takai", spanish: "caro", korean: "비싼", koreanReading: "bissan", imageCode: "1f4b8" },
  { number: 90, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "yasui", spanish: "barato", korean: "싼", koreanReading: "ssan", imageCode: "1f4b5" },
  { number: 91, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "ikura", spanish: "cuánto", korean: "얼마", koreanReading: "eolma", imageCode: "1f4b1" },
  { number: 92, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "kau", spanish: "comprar", korean: "사다", koreanReading: "sada", imageCode: "1f6d2" },
  { number: 93, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "kaado", spanish: "tarjeta", korean: "카드", koreanReading: "kadeu", imageCode: "1f4b3" },
  { number: 94, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "genkin", spanish: "efectivo", korean: "현금", koreanReading: "hyeongeum", imageCode: "1f4b5" },
  { number: 95, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "receipto", spanish: "recibo", korean: "영수증", koreanReading: "yeongsujeung", imageCode: "1f9fe" },
  { number: 96, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "takusan", spanish: "mucho", korean: "많이", koreanReading: "mani", imageCode: "1f4e6" },
  { number: 97, block: "G", category: "Dinero y compras", categoryKo: "돈과 쇼핑", romaji: "sukoshi", spanish: "un poco", korean: "조금", koreanReading: "jogeum", imageCode: "1f538" },
  { number: 98, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "kyou", spanish: "hoy", korean: "오늘", koreanReading: "oneul", imageCode: "1f4c5" },
  { number: 99, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "ashita", spanish: "mañana", korean: "내일", koreanReading: "naeil", imageCode: "1f305" },
  { number: 100, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "kinou", spanish: "ayer", korean: "어제", koreanReading: "eoje", imageCode: "23ea" },
  { number: 101, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "ima", spanish: "ahora", korean: "지금", koreanReading: "jigeum", imageCode: "23f0" },
  { number: 102, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "ato", spanish: "después", korean: "나중에", koreanReading: "najunge", imageCode: "23ed" },
  { number: 103, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "mae", spanish: "antes", korean: "전에", koreanReading: "jeone", imageCode: "23ee" },
  { number: 104, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "asa", spanish: "mañana (temprano)", korean: "아침", koreanReading: "achim", imageCode: "1f305" },
  { number: 105, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "hiru", spanish: "tarde", korean: "오후", koreanReading: "ohu", imageCode: "1f31e" },
  { number: 106, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "yoru", spanish: "noche", korean: "밤", koreanReading: "bam", imageCode: "1f319" },
  { number: 107, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "jikan", spanish: "tiempo", korean: "시간", koreanReading: "sigan", imageCode: "23f0" },
  { number: 108, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "toki", spanish: "momento", korean: "순간", koreanReading: "sungan", imageCode: "23f1" },
  { number: 109, block: "H", category: "Tiempo", categoryKo: "시간", romaji: "raishuu", spanish: "próxima semana", korean: "다음 주", koreanReading: "daeum ju", imageCode: "1f4c6" },
  { number: 110, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "nani", spanish: "qué", korean: "무엇", koreanReading: "mueot", imageCode: "2753" },
  { number: 111, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "dare", spanish: "quién", korean: "누구", koreanReading: "nugu", imageCode: "1f464" },
  { number: 112, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "doko", spanish: "dónde", korean: "어디", koreanReading: "eodi", imageCode: "1f4cd" },
  { number: 113, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "itsu", spanish: "cuándo", korean: "언제", koreanReading: "eonje", imageCode: "1f4c5" },
  { number: 114, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "naze", spanish: "por qué", korean: "왜", koreanReading: "wae", imageCode: "1f914" },
  { number: 115, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "dou", spanish: "cómo", korean: "어떻게", koreanReading: "eotteoke", imageCode: "2699" },
  { number: 116, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "dochira", spanish: "cuál", korean: "어느 것", koreanReading: "eoneu geot", imageCode: "1f500" },
  { number: 117, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "donna", spanish: "qué tipo", korean: "어떤 종류", koreanReading: "eotteon jongnyu", imageCode: "1f3f7" },
  { number: 118, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "ikutsu", spanish: "cuántos", korean: "몇 개", koreanReading: "myeot gae", imageCode: "1f522" },
  { number: 119, block: "I", category: "Preguntas poderosas", categoryKo: "핵심 질문", romaji: "donna hito", spanish: "qué tipo de persona", korean: "어떤 사람", koreanReading: "eotteon saram", imageCode: "1f9d1" },
  { number: 120, block: "J", category: "Emociones", categoryKo: "감정", romaji: "ureshii", spanish: "feliz", korean: "행복한", koreanReading: "haengbokhan", imageCode: "1f604" },
  { number: 121, block: "J", category: "Emociones", categoryKo: "감정", romaji: "sabishii", spanish: "triste", korean: "슬픈", koreanReading: "seulpeun", imageCode: "1f622" },
  { number: 122, block: "J", category: "Emociones", categoryKo: "감정", romaji: "tanoshii", spanish: "divertido", korean: "재미있는", koreanReading: "jaemiinneun", imageCode: "1f389" },
  { number: 123, block: "J", category: "Emociones", categoryKo: "감정", romaji: "kowai", spanish: "miedo", korean: "두려움", koreanReading: "duryeoum", imageCode: "1f631" },
  { number: 124, block: "J", category: "Emociones", categoryKo: "감정", romaji: "shinpai", spanish: "preocupación", korean: "걱정", koreanReading: "geokjeong", imageCode: "1f61f" },
  { number: 125, block: "J", category: "Emociones", categoryKo: "감정", romaji: "anshin", spanish: "tranquilidad", korean: "평온", koreanReading: "pyeongon", imageCode: "1f60c" },
  { number: 126, block: "J", category: "Emociones", categoryKo: "감정", romaji: "komaru", spanish: "problema", korean: "문제", koreanReading: "munje", imageCode: "26a0" },
  { number: 127, block: "J", category: "Emociones", categoryKo: "감정", romaji: "okoru", spanish: "enojarse", korean: "화나다", koreanReading: "hwanada", imageCode: "1f620" },
  { number: 128, block: "J", category: "Emociones", categoryKo: "감정", romaji: "yorokobu", spanish: "alegrarse", korean: "기뻐하다", koreanReading: "gippeohada", imageCode: "1f60a" },
  { number: 129, block: "J", category: "Emociones", categoryKo: "감정", romaji: "warau", spanish: "reír", korean: "웃다", koreanReading: "utda", imageCode: "1f606" },
  { number: 130, block: "J", category: "Emociones", categoryKo: "감정", romaji: "naku", spanish: "llorar", korean: "울다", koreanReading: "ulda", imageCode: "1f62d" },
  { number: 131, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "ai", spanish: "amor", korean: "사랑", koreanReading: "sarang", imageCode: "2764" },
  { number: 132, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "koi", spanish: "enamoramiento", korean: "연애", koreanReading: "yeonae", imageCode: "1f498" },
  { number: 133, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "deeto", spanish: "cita", korean: "데이트", koreanReading: "deiteu", imageCode: "1f4c5" },
  { number: 134, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "egao", spanish: "sonrisa", korean: "미소", koreanReading: "miso", imageCode: "1f60a" },
  { number: 135, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "kokoro", spanish: "corazón", korean: "마음", koreanReading: "maeum", imageCode: "2764" },
  { number: 136, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "kimochi", spanish: "sentimiento", korean: "감정", koreanReading: "gamjeong", imageCode: "1f49f" },
  { number: 137, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "shiawase", spanish: "felicidad", korean: "행복", koreanReading: "haengbok", imageCode: "1f60a" },
  { number: 138, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "yume", spanish: "sueño", korean: "꿈", koreanReading: "kkum", imageCode: "1f4ad" },
  { number: 139, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "kibou", spanish: "esperanza", korean: "희망", koreanReading: "huimang", imageCode: "1f54a" },
  { number: 140, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "yakusoku", spanish: "promesa", korean: "약속", koreanReading: "yaksok", imageCode: "1f91d" },
  { number: 141, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "himitsu", spanish: "secreto", korean: "비밀", koreanReading: "bimil", imageCode: "1f92b" },
  { number: 142, block: "K", category: "Relaciones y afecto", categoryKo: "관계와 애정", romaji: "aishiteru", spanish: "te amo", korean: "사랑해", koreanReading: "saranghae", imageCode: "1f970" },
  { number: 143, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "suki", spanish: "gustar", korean: "좋아하다", koreanReading: "joahada", imageCode: "1f44d" },
  { number: 144, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "kirai", spanish: "no gustar", korean: "싫어하다", koreanReading: "sireohada", imageCode: "1f44e" },
  { number: 145, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "ongaku", spanish: "música", korean: "음악", koreanReading: "eumak", imageCode: "1f3b5" },
  { number: 146, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "uta", spanish: "canción", korean: "노래", koreanReading: "norae", imageCode: "1f3a4" },
  { number: 147, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "piano", spanish: "piano", korean: "피아노", koreanReading: "piano", imageCode: "1f3b9" },
  { number: 148, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "eiga", spanish: "película", korean: "영화", koreanReading: "yeonghwa", imageCode: "1f3ac" },
  { number: 149, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "hon", spanish: "libro", korean: "책", koreanReading: "chaek", imageCode: "1f4d6" },
  { number: 150, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "shashin", spanish: "foto", korean: "사진", koreanReading: "sajin", imageCode: "1f4f7" },
  { number: 151, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "odoru", spanish: "bailar", korean: "춤추다", koreanReading: "chumchuda", imageCode: "1f483" },
  { number: 152, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "asobu", spanish: "jugar", korean: "놀다", koreanReading: "nolda", imageCode: "1f3ae" },
  { number: 153, block: "L", category: "Gustos y entretenimiento", categoryKo: "취향과 오락", romaji: "ryokou", spanish: "viaje", korean: "여행", koreanReading: "yeohaeng", imageCode: "1f9f3" },
  { number: 154, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "shigoto", spanish: "trabajo", korean: "일", koreanReading: "il", imageCode: "1f4bc" },
  { number: 155, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "kaigi", spanish: "reunión", korean: "회의", koreanReading: "hoeui", imageCode: "1f465" },
  { number: 156, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "mondai", spanish: "problema", korean: "문제", koreanReading: "munje", imageCode: "26a0" },
  { number: 157, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "keiken", spanish: "experiencia", korean: "경험", koreanReading: "gyeongheom", imageCode: "1f9ed" },
  { number: 158, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "chance", spanish: "oportunidad", korean: "기회", koreanReading: "gihoe", imageCode: "1f513" },
  { number: 159, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "seikou", spanish: "éxito", korean: "성공", koreanReading: "seonggong", imageCode: "1f3c6" },
  { number: 160, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "shippai", spanish: "fracaso", korean: "실패", koreanReading: "silpae", imageCode: "274c" },
  { number: 161, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "benkyou", spanish: "estudio", korean: "공부", koreanReading: "gongbu", imageCode: "1f4da" },
  { number: 162, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "narau", spanish: "aprender", korean: "배우다", koreanReading: "baeuda", imageCode: "1f393" },
  { number: 163, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "oshieru", spanish: "enseñar", korean: "가르치다", koreanReading: "gareuchida", imageCode: "1f3eb" },
  { number: 164, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "renshuu", spanish: "práctica", korean: "연습", koreanReading: "yeonseup", imageCode: "270d" },
  { number: 165, block: "M", category: "Trabajo y estudio", categoryKo: "일과 공부", romaji: "jouzu", spanish: "hábil", korean: "능숙한", koreanReading: "neungsukhan", imageCode: "1f3af" },
  { number: 166, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "kirei", spanish: "bonito", korean: "예쁜", koreanReading: "yeppeun", imageCode: "2728" },
  { number: 167, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "kawaii", spanish: "lindo", korean: "귀여운", koreanReading: "gwiyeoun", imageCode: "1f970" },
  { number: 168, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "kakkoii", spanish: "atractivo", korean: "매력적인", koreanReading: "maeryeokjeogin", imageCode: "1f60e" },
  { number: 169, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "suteki", spanish: "encantador", korean: "사랑스러운", koreanReading: "sarangseureoun", imageCode: "1f496" },
  { number: 170, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "ookii", spanish: "grande", korean: "큰", koreanReading: "keun", imageCode: "1f418" },
  { number: 171, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "chiisai", spanish: "pequeño", korean: "작은", koreanReading: "jageun", imageCode: "1f41c" },
  { number: 172, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "atarashii", spanish: "nuevo", korean: "새로운", koreanReading: "saeroun", imageCode: "1f195" },
  { number: 173, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "furui", spanish: "viejo", korean: "오래된", koreanReading: "oraedoen", imageCode: "1f3da" },
  { number: 174, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "muzukashii", spanish: "difícil", korean: "어려운", koreanReading: "eoryeoun", imageCode: "1f9e9" },
  { number: 175, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "kantan", spanish: "fácil", korean: "쉬운", koreanReading: "swiun", imageCode: "2705" },
  { number: 176, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "sugoi", spanish: "increíble", korean: "놀라운", koreanReading: "nollaun", imageCode: "1f929" },
  { number: 177, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "benri", spanish: "conveniente", korean: "편리한", koreanReading: "pyeollihan", imageCode: "1f527" },
  { number: 178, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "taihen", spanish: "complicado", korean: "복잡한", koreanReading: "bokjaphan", imageCode: "1f635" },
  { number: 179, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "hen", spanish: "raro", korean: "이상한", koreanReading: "isanghan", imageCode: "1f928" },
  { number: 180, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "akarui", spanish: "alegre / brillante", korean: "밝은", koreanReading: "balgeun", imageCode: "1f31e" },
  { number: 181, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "kurai", spanish: "oscuro / triste", korean: "어두운", koreanReading: "eoduun", imageCode: "1f311" },
  { number: 182, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "shizuka", spanish: "tranquilo", korean: "조용한", koreanReading: "joyonghan", imageCode: "1f92b" },
  { number: 183, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "urusai", spanish: "ruidoso", korean: "시끄러운", koreanReading: "sikkeureoun", imageCode: "1f50a" },
  { number: 184, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "nigiyaka", spanish: "animado", korean: "활기찬", koreanReading: "hwalgichan", imageCode: "1f389" },
  { number: 185, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "omoi", spanish: "pesado", korean: "무거운", koreanReading: "mugeoun", imageCode: "1f4aa" },
  { number: 186, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "karui", spanish: "ligero", korean: "가벼운", koreanReading: "gabyeoun", imageCode: "1f388" },
  { number: 187, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "nagai", spanish: "largo", korean: "긴", koreanReading: "gin", imageCode: "1f4cf" },
  { number: 188, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "mijikai", spanish: "corto", korean: "짧은", koreanReading: "jjalbeun", imageCode: "2702" },
  { number: 189, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "anzen", spanish: "seguro", korean: "안전한", koreanReading: "anjeonhan", imageCode: "1f6e1" },
  { number: 190, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "abunai", spanish: "peligroso", korean: "위험한", koreanReading: "wiheomhan", imageCode: "26a0" },
  { number: 191, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "majime", spanish: "serio", korean: "진지한", koreanReading: "jinjihan", imageCode: "1f9d1" },
  { number: 192, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "yasashii", spanish: "amable", korean: "친절한", koreanReading: "chinjeolhan", imageCode: "1f917" },
  { number: 193, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "shinsetsu", spanish: "gentil", korean: "상냥한", koreanReading: "sangnyanghan", imageCode: "1f49a" },
  { number: 194, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "kibishii", spanish: "estricto", korean: "엄격한", koreanReading: "eomgyeokhan", imageCode: "1f6a8" },
  { number: 195, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "tokubetsu", spanish: "especial", korean: "특별한", koreanReading: "teukbyeolhan", imageCode: "2b50" },
  { number: 196, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "taisetsu", spanish: "importante", korean: "중요한", koreanReading: "jungyohan", imageCode: "1f48e" },
  { number: 197, block: "N", category: "Adjetivos clave", categoryKo: "핵심 형용사", romaji: "utsukushii", spanish: "hermoso", korean: "아름다운", koreanReading: "areumdaun", imageCode: "1f338" },
  { number: 198, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "yama", spanish: "montaña", korean: "산", koreanReading: "san", imageCode: "26f0" },
  { number: 199, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "umi", spanish: "mar", korean: "바다", koreanReading: "bada", imageCode: "1f30a" },
  { number: 200, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "sora", spanish: "cielo", korean: "하늘", koreanReading: "haneul", imageCode: "2601" },
  { number: 201, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "ame", spanish: "lluvia", korean: "비", koreanReading: "bi", imageCode: "1f327" },
  { number: 202, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "taiyou", spanish: "sol", korean: "해", koreanReading: "hae", imageCode: "2600" },
  { number: 203, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "tsuki", spanish: "luna", korean: "달", koreanReading: "dal", imageCode: "1f319" },
  { number: 204, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "hoshi", spanish: "estrella", korean: "별", koreanReading: "byeol", imageCode: "2b50" },
  { number: 205, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "kaze", spanish: "viento", korean: "바람", koreanReading: "baram", imageCode: "1f32c" },
  { number: 206, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "hana", spanish: "flor", korean: "꽃", koreanReading: "kkot", imageCode: "1f33c" },
  { number: 207, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "ki", spanish: "árbol", korean: "나무", koreanReading: "namu", imageCode: "1f333" },
  { number: 208, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "hi", spanish: "fuego", korean: "불", koreanReading: "bul", imageCode: "1f525" },
  { number: 209, block: "O", category: "Naturaleza y mundo", categoryKo: "자연과 세계", romaji: "tsuchi", spanish: "tierra", korean: "땅", koreanReading: "ttang", imageCode: "1f30d" },
  { number: 210, block: "P", category: "Animales", categoryKo: "동물", romaji: "inu", spanish: "perro", korean: "개", koreanReading: "gae", imageCode: "1f436" },
  { number: 211, block: "P", category: "Animales", categoryKo: "동물", romaji: "neko", spanish: "gato", korean: "고양이", koreanReading: "goyangi", imageCode: "1f431" },
  { number: 212, block: "P", category: "Animales", categoryKo: "동물", romaji: "tori", spanish: "pájaro", korean: "새", koreanReading: "sae", imageCode: "1f426" },
  { number: 213, block: "P", category: "Animales", categoryKo: "동물", romaji: "sakana", spanish: "pez", korean: "물고기", koreanReading: "mulgogi", imageCode: "1f41f" },
  { number: 214, block: "P", category: "Animales", categoryKo: "동물", romaji: "uma", spanish: "caballo", korean: "말", koreanReading: "mal", imageCode: "1f434" },
  { number: 215, block: "P", category: "Animales", categoryKo: "동물", romaji: "usagi", spanish: "conejo", korean: "토끼", koreanReading: "tokki", imageCode: "1f430" },
  { number: 216, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "au", spanish: "encontrarse", korean: "만나다", koreanReading: "mannada", imageCode: "1f91d" },
  { number: 217, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "wakareru", spanish: "separarse", korean: "헤어지다", koreanReading: "heeojida", imageCode: "1f44b" },
  { number: 218, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "ageru", spanish: "dar", korean: "주다", koreanReading: "juda", imageCode: "1f381" },
  { number: 219, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "morau", spanish: "recibir", korean: "받다", koreanReading: "batda", imageCode: "1f4e5" },
  { number: 220, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "kureru", spanish: "darme", korean: "나에게 주다", koreanReading: "naege juda", imageCode: "1f64f" },
  { number: 221, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "ikou", spanish: "vamos", korean: "가자", koreanReading: "gaja", imageCode: "1f449" },
  { number: 222, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "kaette", spanish: "vuelve", korean: "돌아와", koreanReading: "dorawa", imageCode: "1f504" },
  { number: 223, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "aitai", spanish: "quiero verte", korean: "보고 싶어", koreanReading: "bogo sipeo", imageCode: "1f440" },
  { number: 224, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "shinjiru", spanish: "confiar", korean: "믿다", koreanReading: "mitda", imageCode: "1f91d" },
  { number: 225, block: "Q", category: "Movimiento social", categoryKo: "사회적 움직임", romaji: "tasukaru", spanish: "recibir ayuda", korean: "도움을 받다", koreanReading: "doumeul batda", imageCode: "1f198" },
  { number: 226, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "zettai", spanish: "definitivamente", korean: "반드시", koreanReading: "bandeusi", imageCode: "2705" },
  { number: 227, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "mada", spanish: "todavía", korean: "아직", koreanReading: "ajik", imageCode: "23f3" },
  { number: 228, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "mou", spanish: "ya", korean: "이미", koreanReading: "imi", imageCode: "2705" },
  { number: 229, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "zenzen", spanish: "para nada", korean: "전혀", koreanReading: "jeonhyeo", imageCode: "1f6ab" },
  { number: 230, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "itsumo", spanish: "siempre", korean: "항상", koreanReading: "hangsang", imageCode: "267e" },
  { number: 231, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "tokidoki", spanish: "a veces", korean: "가끔", koreanReading: "gakkeum", imageCode: "1f501" },
  { number: 232, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "amari", spanish: "no mucho", korean: "별로", koreanReading: "byeollo", imageCode: "1f538" },
  { number: 233, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "zenbu", spanish: "todo", korean: "모두", koreanReading: "modu", imageCode: "1f30d" },
  { number: 234, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "minna", spanish: "todos", korean: "모두들", koreanReading: "modudeul", imageCode: "1f465" },
  { number: 235, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "kondo", spanish: "próxima vez", korean: "다음번", koreanReading: "daeumbeon", imageCode: "1f4c6" },
  { number: 236, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "saigo", spanish: "final", korean: "끝", koreanReading: "kkeut", imageCode: "1f3c1" },
  { number: 237, block: "R", category: "Expresiones frecuentes", categoryKo: "자주 쓰는 표현", romaji: "hajime", spanish: "comienzo", korean: "시작", koreanReading: "sijak", imageCode: "1f530" },
  { number: 238, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "hima", spanish: "tiempo libre", korean: "자유 시간", koreanReading: "jayu sigan", imageCode: "1f3d6" },
  { number: 239, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "kyuujitsu", spanish: "día libre", korean: "쉬는 날", koreanReading: "swineun nal", imageCode: "1f3dd" },
  { number: 240, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "shuumatsu", spanish: "fin de semana", korean: "주말", koreanReading: "jumal", imageCode: "1f5d3" },
  { number: 241, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "tanjoubi", spanish: "cumpleaños", korean: "생일", koreanReading: "saengil", imageCode: "1f382" },
  { number: 242, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "omatsuri", spanish: "festival", korean: "축제", koreanReading: "chukje", imageCode: "1f38f" },
  { number: 243, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "paatii", spanish: "fiesta", korean: "파티", koreanReading: "pati", imageCode: "1f389" },
  { number: 244, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "konban", spanish: "esta noche", korean: "오늘 밤", koreanReading: "oneul bam", imageCode: "1f303" },
  { number: 245, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "kesa", spanish: "esta mañana", korean: "오늘 아침", koreanReading: "oneul achim", imageCode: "1f305" },
  { number: 246, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "mayoi", spanish: "perdido", korean: "길을 잃은", koreanReading: "gireul ireun", imageCode: "1f9ed" },
  { number: 247, block: "S", category: "Vida social", categoryKo: "사회 생활", romaji: "denwa", spanish: "llamada", korean: "전화", koreanReading: "jeonhwa", imageCode: "1f4de" },
  { number: 248, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "miru", spanish: "ver", korean: "보다", koreanReading: "boda", imageCode: "1f440" },
  { number: 249, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "yomu", spanish: "leer", korean: "읽다", koreanReading: "ikda", imageCode: "1f4d6" },
  { number: 250, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "noru", spanish: "subir / montar", korean: "타다", koreanReading: "tada", imageCode: "1f68c" },
  { number: 251, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "oriru", spanish: "bajar", korean: "내려가다", koreanReading: "naeryeogada", imageCode: "1f53d" },
  { number: 252, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "okiru", spanish: "despertar", korean: "깨다", koreanReading: "kkaeda", imageCode: "23f0" },
  { number: 253, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "nareru", spanish: "acostumbrarse", korean: "익숙해지다", koreanReading: "iksukhaejida", imageCode: "1f501" },
  { number: 254, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "hajimaru", spanish: "empezar", korean: "시작하다", koreanReading: "sijakhada", imageCode: "25b6" },
  { number: 255, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "owaru", spanish: "terminar", korean: "끝내다", koreanReading: "kkeutnaeda", imageCode: "1f3c1" },
  { number: 256, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "tsuzuku", spanish: "continuar", korean: "계속하다", koreanReading: "gyesokhada", imageCode: "27a1" },
  { number: 257, block: "T", category: "Acciones extra", categoryKo: "추가 행동", romaji: "yoroshiku", spanish: "buen trato / encantado", korean: "잘 부탁합니다", koreanReading: "jal butakhamnida", imageCode: "1f91d" },
  { number: 258, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "densha", spanish: "tren", korean: "기차", koreanReading: "gicha", imageCode: "1f686" },
  { number: 259, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "basu", spanish: "bus", korean: "버스", koreanReading: "beoseu", imageCode: "1f68c" },
  { number: 260, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "kuruma", spanish: "carro", korean: "자동차", koreanReading: "jadongcha", imageCode: "1f697" },
  { number: 261, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "jitensha", spanish: "bicicleta", korean: "자전거", koreanReading: "jajeongeo", imageCode: "1f6b2" },
  { number: 262, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "hikouki", spanish: "avión", korean: "비행기", koreanReading: "bihaenggi", imageCode: "2708" },
  { number: 263, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "taxi", spanish: "taxi", korean: "택시", koreanReading: "taeksi", imageCode: "1f695" },
  { number: 264, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "michi", spanish: "calle / camino", korean: "길", koreanReading: "gil", imageCode: "1f6e3" },
  { number: 265, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "chikaku", spanish: "cerca", korean: "가까운", koreanReading: "gakkaun", imageCode: "1f4cd" },
  { number: 266, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "tooi", spanish: "lejos", korean: "먼", koreanReading: "meon", imageCode: "1f5fa" },
  { number: 267, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "hayai", spanish: "rápido / temprano", korean: "빠른", koreanReading: "ppareun", imageCode: "1f3c3" },
  { number: 268, block: "U", category: "Transporte y movimiento", categoryKo: "교통과 이동", romaji: "osoi", spanish: "lento / tarde", korean: "느린", koreanReading: "neurin", imageCode: "1f422" },
  { number: 269, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "kaban", spanish: "bolso", korean: "가방", koreanReading: "gabang", imageCode: "1f45c" },
  { number: 270, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "kagi", spanish: "llave", korean: "열쇠", koreanReading: "yeolsoe", imageCode: "1f511" },
  { number: 271, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "kasa", spanish: "paraguas", korean: "우산", koreanReading: "usan", imageCode: "2602" },
  { number: 272, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "kutsu", spanish: "zapatos", korean: "신발", koreanReading: "sinbal", imageCode: "1f45f" },
  { number: 273, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "fuku", spanish: "ropa", korean: "옷", koreanReading: "ot", imageCode: "1f455" },
  { number: 274, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "isu", spanish: "silla", korean: "의자", koreanReading: "uija", imageCode: "1f4ba" },
  { number: 275, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "tsukue", spanish: "mesa / escritorio", korean: "책상", koreanReading: "chaeksang", imageCode: "1f4bb" },
  { number: 276, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "doa", spanish: "puerta", korean: "문", koreanReading: "mun", imageCode: "1f6aa" },
  { number: 277, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "mado", spanish: "ventana", korean: "창문", koreanReading: "changmun", imageCode: "1fa9f" },
  { number: 278, block: "V", category: "Casa y objetos diarios", categoryKo: "집과 일상 물건", romaji: "heya", spanish: "habitación", korean: "방", koreanReading: "bang", imageCode: "1f6cf" },
  { number: 279, block: "W", category: "Tecnología y vida moderna", categoryKo: "기술과 현대 생활", romaji: "wi-fi", spanish: "wifi", korean: "와이파이", koreanReading: "waipai", imageCode: "1f4f6" },
  { number: 280, block: "W", category: "Tecnología y vida moderna", categoryKo: "기술과 현대 생활", romaji: "pasokon", spanish: "computador", korean: "컴퓨터", koreanReading: "keompyuteo", imageCode: "1f4bb" },
  { number: 281, block: "W", category: "Tecnología y vida moderna", categoryKo: "기술과 현대 생활", romaji: "apuri", spanish: "aplicación", korean: "앱", koreanReading: "aep", imageCode: "1f4f1" },
  { number: 282, block: "W", category: "Tecnología y vida moderna", categoryKo: "기술과 현대 생활", romaji: "kamera", spanish: "cámara", korean: "카메라", koreanReading: "kamera", imageCode: "1f4f7" },
  { number: 283, block: "W", category: "Tecnología y vida moderna", categoryKo: "기술과 현대 생활", romaji: "terebi", spanish: "televisión", korean: "텔레비전", koreanReading: "tellebijeon", imageCode: "1f4fa" },
  { number: 284, block: "W", category: "Tecnología y vida moderna", categoryKo: "기술과 현대 생활", romaji: "rajio", spanish: "radio", korean: "라디오", koreanReading: "radio", imageCode: "1f4fb" },
  { number: 285, block: "W", category: "Tecnología y vida moderna", categoryKo: "기술과 현대 생활", romaji: "denchi", spanish: "batería", korean: "배터리", koreanReading: "baeteori", imageCode: "1f50b" },
  { number: 286, block: "W", category: "Tecnología y vida moderna", categoryKo: "기술과 현대 생활", romaji: "juuden", spanish: "cargar batería", korean: "충전하다", koreanReading: "chungjeonhada", imageCode: "1f50c" },
  { number: 287, block: "X", category: "Salud y emergencia", categoryKo: "건강과 응급", romaji: "itai", spanish: "dolor", korean: "통증", koreanReading: "tongjeung", imageCode: "1f915" },
  { number: 288, block: "X", category: "Salud y emergencia", categoryKo: "건강과 응급", romaji: "daijoubu", spanish: "estar bien", korean: "괜찮다", koreanReading: "gwaenchanta", imageCode: "2705" },
  { number: 289, block: "X", category: "Salud y emergencia", categoryKo: "건강과 응급", romaji: "kusuri", spanish: "medicina", korean: "약", koreanReading: "yak", imageCode: "1f48a" },
  { number: 290, block: "X", category: "Salud y emergencia", categoryKo: "건강과 응급", romaji: "byouki", spanish: "enfermedad", korean: "병", koreanReading: "byeong", imageCode: "1f912" },
  { number: 291, block: "X", category: "Salud y emergencia", categoryKo: "건강과 응급", romaji: "jiko", spanish: "accidente", korean: "사고", koreanReading: "sago", imageCode: "1f6a8" },
  { number: 292, block: "X", category: "Salud y emergencia", categoryKo: "건강과 응급", romaji: "keisatsu", spanish: "policía", korean: "경찰", koreanReading: "gyeongchal", imageCode: "1f693" },
  { number: 293, block: "X", category: "Salud y emergencia", categoryKo: "건강과 응급", romaji: "tasukete", spanish: "ayúdame", korean: "도와줘", koreanReading: "dowajwo", imageCode: "1f198" },
  { number: 294, block: "X", category: "Salud y emergencia", categoryKo: "건강과 응급", romaji: "abunai", spanish: "peligroso", korean: "위험한", koreanReading: "wiheomhan", imageCode: "26a0" },
  { number: 295, block: "X", category: "Salud y emergencia", categoryKo: "건강과 응급", romaji: "anzen", spanish: "seguro", korean: "안전한", koreanReading: "anjeonhan", imageCode: "1f6e1" },
  { number: 296, block: "Y", category: "Fuerza interior", categoryKo: "내면의 힘", romaji: "jiyuu", spanish: "libertad", korean: "자유", koreanReading: "jayu", imageCode: "1f54a" },
  { number: 297, block: "Y", category: "Fuerza interior", categoryKo: "내면의 힘", romaji: "chikara", spanish: "fuerza", korean: "힘", koreanReading: "him", imageCode: "1f4aa" },
  { number: 298, block: "Y", category: "Fuerza interior", categoryKo: "내면의 힘", romaji: "yuuki", spanish: "valentía", korean: "용기", koreanReading: "yonggi", imageCode: "1f981" },
  { number: 299, block: "Y", category: "Fuerza interior", categoryKo: "내면의 힘", romaji: "genjitsu", spanish: "realidad", korean: "현실", koreanReading: "hyeonsil", imageCode: "1f441" },
  { number: 300, block: "Y", category: "Fuerza interior", categoryKo: "내면의 힘", romaji: "mirai", spanish: "futuro", korean: "미래", koreanReading: "mirae", imageCode: "1f52e" },
] satisfies StarterVocabularyEntry[];

export function getStarterImageUrl(imageCode: string): string {
  return `${TWEMOJI_BASE_URL}/${imageCode}.svg`;
}

export function getJaEsStarterCardId(number: number): string {
  return `00000000-0000-4000-8000-${String(number).padStart(12, "0")}`;
}

export function getKoEsStarterCardId(number: number): string {
  return `00000000-0000-4001-8000-${String(number).padStart(12, "0")}`;
}

export function getStarterCreatedAt(number: number): string {
  return new Date(Date.UTC(2026, 0, 1, 0, 0, number)).toISOString();
}
