import type { VocabularyCard } from "@/types/card";

export interface StarterJaEsEntry {
  number: number;
  block: string;
  category: string;
  romaji: string;
  spanish: string;
  imageCode: string;
}

const TWEMOJI_BASE_URL = "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg";

export const starterJaEsEntries = [
  { number: 1, block: "A", category: "Identidad personal", romaji: "watashi", spanish: "yo", imageCode: "1f464" },
  { number: 2, block: "A", category: "Identidad personal", romaji: "namae", spanish: "nombre", imageCode: "1f4db" },
  { number: 3, block: "A", category: "Identidad personal", romaji: "nenrei", spanish: "edad", imageCode: "1f382" },
  { number: 4, block: "A", category: "Identidad personal", romaji: "hito", spanish: "persona", imageCode: "1f9d1" },
  { number: 5, block: "A", category: "Identidad personal", romaji: "otoko", spanish: "hombre", imageCode: "1f468" },
  { number: 6, block: "A", category: "Identidad personal", romaji: "onna", spanish: "mujer", imageCode: "1f469" },
  { number: 7, block: "A", category: "Identidad personal", romaji: "kodomo", spanish: "ni?o", imageCode: "1f9d2" },
  { number: 8, block: "A", category: "Identidad personal", romaji: "tomodachi", spanish: "amigo", imageCode: "1f91d" },
  { number: 9, block: "A", category: "Identidad personal", romaji: "kazoku", spanish: "familia", imageCode: "1f46a" },
  { number: 10, block: "A", category: "Identidad personal", romaji: "otousan", spanish: "padre", imageCode: "1f468" },
  { number: 11, block: "A", category: "Identidad personal", romaji: "okaasan", spanish: "madre", imageCode: "1f469" },
  { number: 12, block: "A", category: "Identidad personal", romaji: "ani", spanish: "hermano mayor", imageCode: "1f466" },
  { number: 13, block: "A", category: "Identidad personal", romaji: "imouto", spanish: "hermana menor", imageCode: "1f467" },
  { number: 14, block: "A", category: "Identidad personal", romaji: "sensei", spanish: "profesor", imageCode: "1f3eb" },
  { number: 15, block: "A", category: "Identidad personal", romaji: "koibito", spanish: "pareja", imageCode: "1f491" },
  { number: 16, block: "B", category: "Respuestas inmediatas", romaji: "hai", spanish: "s?", imageCode: "2705" },
  { number: 17, block: "B", category: "Respuestas inmediatas", romaji: "iie", spanish: "no", imageCode: "274c" },
  { number: 18, block: "B", category: "Respuestas inmediatas", romaji: "daijoubu", spanish: "est? bien", imageCode: "1f197" },
  { number: 19, block: "B", category: "Respuestas inmediatas", romaji: "dame", spanish: "no se puede", imageCode: "1f6ab" },
  { number: 20, block: "B", category: "Respuestas inmediatas", romaji: "ii", spanish: "bien", imageCode: "1f44d" },
  { number: 21, block: "B", category: "Respuestas inmediatas", romaji: "sumimasen", spanish: "disculpa", imageCode: "1f64f" },
  { number: 22, block: "B", category: "Respuestas inmediatas", romaji: "gomen", spanish: "perd?n", imageCode: "1f64f" },
  { number: 23, block: "B", category: "Respuestas inmediatas", romaji: "onegai", spanish: "por favor", imageCode: "1f64f" },
  { number: 24, block: "B", category: "Respuestas inmediatas", romaji: "hontou", spanish: "verdad", imageCode: "1f4af" },
  { number: 25, block: "B", category: "Respuestas inmediatas", romaji: "mochiron", spanish: "claro", imageCode: "1f44c" },
  { number: 26, block: "B", category: "Respuestas inmediatas", romaji: "tabun", spanish: "tal vez", imageCode: "1f914" },
  { number: 27, block: "B", category: "Respuestas inmediatas", romaji: "yokatta", spanish: "qu? bueno", imageCode: "1f60a" },
  { number: 28, block: "B", category: "Respuestas inmediatas", romaji: "iya", spanish: "no quiero", imageCode: "1f645" },
  { number: 29, block: "B", category: "Respuestas inmediatas", romaji: "mate", spanish: "espera", imageCode: "23f3" },
  { number: 30, block: "B", category: "Respuestas inmediatas", romaji: "kite", spanish: "ven", imageCode: "1f44b" },
  { number: 31, block: "C", category: "Entender y hablar", romaji: "wakaru", spanish: "entender", imageCode: "1f4a1" },
  { number: 32, block: "C", category: "Entender y hablar", romaji: "wakaranai", spanish: "no entender", imageCode: "2753" },
  { number: 33, block: "C", category: "Entender y hablar", romaji: "hanasu", spanish: "hablar", imageCode: "1f5e3" },
  { number: 34, block: "C", category: "Entender y hablar", romaji: "kiku", spanish: "escuchar / preguntar", imageCode: "1f442" },
  { number: 35, block: "C", category: "Entender y hablar", romaji: "koe", spanish: "voz", imageCode: "1f3a4" },
  { number: 36, block: "C", category: "Entender y hablar", romaji: "oto", spanish: "sonido", imageCode: "1f50a" },
  { number: 37, block: "C", category: "Entender y hablar", romaji: "hanashi", spanish: "conversaci?n", imageCode: "1f4ac" },
  { number: 38, block: "C", category: "Entender y hablar", romaji: "shitsumon", spanish: "pregunta", imageCode: "2753" },
  { number: 39, block: "C", category: "Entender y hablar", romaji: "kotae", spanish: "respuesta", imageCode: "2705" },
  { number: 40, block: "C", category: "Entender y hablar", romaji: "imi", spanish: "significado", imageCode: "1f4d6" },
  { number: 41, block: "C", category: "Entender y hablar", romaji: "denwa", spanish: "tel?fono", imageCode: "1f4de" },
  { number: 42, block: "C", category: "Entender y hablar", romaji: "messeeji", spanish: "mensaje", imageCode: "1f4e9" },
  { number: 43, block: "C", category: "Entender y hablar", romaji: "me-ru", spanish: "correo", imageCode: "2709" },
  { number: 44, block: "C", category: "Entender y hablar", romaji: "kotaeru", spanish: "responder", imageCode: "1f4e8" },
  { number: 45, block: "C", category: "Entender y hablar", romaji: "tazuneru", spanish: "preguntar", imageCode: "1f914" },
  { number: 46, block: "D", category: "Verbos de vida", romaji: "iku", spanish: "ir", imageCode: "1f6b6" },
  { number: 47, block: "D", category: "Verbos de vida", romaji: "kuru", spanish: "venir", imageCode: "1f44b" },
  { number: 48, block: "D", category: "Verbos de vida", romaji: "kaeru", spanish: "volver", imageCode: "1f504" },
  { number: 49, block: "D", category: "Verbos de vida", romaji: "aruku", spanish: "caminar", imageCode: "1f6b6" },
  { number: 50, block: "D", category: "Verbos de vida", romaji: "hashiru", spanish: "correr", imageCode: "1f3c3" },
  { number: 51, block: "D", category: "Verbos de vida", romaji: "hairu", spanish: "entrar", imageCode: "1f6aa" },
  { number: 52, block: "D", category: "Verbos de vida", romaji: "deru", spanish: "salir", imageCode: "1f6aa" },
  { number: 53, block: "D", category: "Verbos de vida", romaji: "matsu", spanish: "esperar", imageCode: "23f3" },
  { number: 54, block: "D", category: "Verbos de vida", romaji: "suru", spanish: "hacer", imageCode: "1f6e0" },
  { number: 55, block: "D", category: "Verbos de vida", romaji: "dekiru", spanish: "poder hacer", imageCode: "1f4aa" },
  { number: 56, block: "D", category: "Verbos de vida", romaji: "dekinai", spanish: "no poder", imageCode: "1f6ab" },
  { number: 57, block: "D", category: "Verbos de vida", romaji: "tsukau", spanish: "usar", imageCode: "1f527" },
  { number: 58, block: "D", category: "Verbos de vida", romaji: "erabu", spanish: "elegir", imageCode: "2611" },
  { number: 59, block: "D", category: "Verbos de vida", romaji: "kimaru", spanish: "decidir", imageCode: "1f3af" },
  { number: 60, block: "D", category: "Verbos de vida", romaji: "ganbatte", spanish: "?nimo", imageCode: "1f44a" },
  { number: 61, block: "E", category: "Cuerpo y necesidades", romaji: "mizu", spanish: "agua", imageCode: "1f4a7" },
  { number: 62, block: "E", category: "Cuerpo y necesidades", romaji: "gohan", spanish: "comida", imageCode: "1f35a" },
  { number: 63, block: "E", category: "Cuerpo y necesidades", romaji: "ocha", spanish: "t?", imageCode: "1f375" },
  { number: 64, block: "E", category: "Cuerpo y necesidades", romaji: "pan", spanish: "pan", imageCode: "1f35e" },
  { number: 65, block: "E", category: "Cuerpo y necesidades", romaji: "onaka", spanish: "est?mago", imageCode: "1f372" },
  { number: 66, block: "E", category: "Cuerpo y necesidades", romaji: "taberu", spanish: "comer", imageCode: "1f374" },
  { number: 67, block: "E", category: "Cuerpo y necesidades", romaji: "nomu", spanish: "beber", imageCode: "1f964" },
  { number: 68, block: "E", category: "Cuerpo y necesidades", romaji: "neru", spanish: "dormir", imageCode: "1f6cc" },
  { number: 69, block: "E", category: "Cuerpo y necesidades", romaji: "nemui", spanish: "sue?o", imageCode: "1f634" },
  { number: 70, block: "E", category: "Cuerpo y necesidades", romaji: "tsukareta", spanish: "cansado", imageCode: "1f62b" },
  { number: 71, block: "E", category: "Cuerpo y necesidades", romaji: "atsui", spanish: "calor", imageCode: "1f525" },
  { number: 72, block: "E", category: "Cuerpo y necesidades", romaji: "samui", spanish: "fr?o", imageCode: "2744" },
  { number: 73, block: "E", category: "Cuerpo y necesidades", romaji: "byouin", spanish: "hospital", imageCode: "1f3e5" },
  { number: 74, block: "E", category: "Cuerpo y necesidades", romaji: "kusuri", spanish: "medicina", imageCode: "1f48a" },
  { number: 75, block: "E", category: "Cuerpo y necesidades", romaji: "yasumi", spanish: "descanso", imageCode: "1f6cc" },
  { number: 76, block: "F", category: "Lugares importantes", romaji: "ie", spanish: "casa", imageCode: "1f3e0" },
  { number: 77, block: "F", category: "Lugares importantes", romaji: "eki", spanish: "estaci?n", imageCode: "1f689" },
  { number: 78, block: "F", category: "Lugares importantes", romaji: "toire", spanish: "ba?o", imageCode: "1f6bd" },
  { number: 79, block: "F", category: "Lugares importantes", romaji: "mise", spanish: "tienda", imageCode: "1f3ea" },
  { number: 80, block: "F", category: "Lugares importantes", romaji: "resutoran", spanish: "restaurante", imageCode: "1f37d" },
  { number: 81, block: "F", category: "Lugares importantes", romaji: "gakkou", spanish: "escuela", imageCode: "1f3eb" },
  { number: 82, block: "F", category: "Lugares importantes", romaji: "kaisha", spanish: "empresa", imageCode: "1f3e2" },
  { number: 83, block: "F", category: "Lugares importantes", romaji: "michi", spanish: "camino", imageCode: "1f6e3" },
  { number: 84, block: "F", category: "Lugares importantes", romaji: "machi", spanish: "ciudad", imageCode: "1f3d9" },
  { number: 85, block: "F", category: "Lugares importantes", romaji: "mura", spanish: "pueblo", imageCode: "1f3d8" },
  { number: 86, block: "F", category: "Lugares importantes", romaji: "kuni", spanish: "pa?s", imageCode: "1f5fa" },
  { number: 87, block: "F", category: "Lugares importantes", romaji: "sekai", spanish: "mundo", imageCode: "1f30d" },
  { number: 88, block: "G", category: "Dinero y compras", romaji: "okane", spanish: "dinero", imageCode: "1f4b0" },
  { number: 89, block: "G", category: "Dinero y compras", romaji: "takai", spanish: "caro", imageCode: "1f4b8" },
  { number: 90, block: "G", category: "Dinero y compras", romaji: "yasui", spanish: "barato", imageCode: "1f4b5" },
  { number: 91, block: "G", category: "Dinero y compras", romaji: "ikura", spanish: "cu?nto", imageCode: "1f4b1" },
  { number: 92, block: "G", category: "Dinero y compras", romaji: "kau", spanish: "comprar", imageCode: "1f6d2" },
  { number: 93, block: "G", category: "Dinero y compras", romaji: "kaado", spanish: "tarjeta", imageCode: "1f4b3" },
  { number: 94, block: "G", category: "Dinero y compras", romaji: "genkin", spanish: "efectivo", imageCode: "1f4b5" },
  { number: 95, block: "G", category: "Dinero y compras", romaji: "receipt", spanish: "recibo", imageCode: "1f9fe" },
  { number: 96, block: "G", category: "Dinero y compras", romaji: "takusan", spanish: "mucho", imageCode: "1f4e6" },
  { number: 97, block: "G", category: "Dinero y compras", romaji: "sukoshi", spanish: "un poco", imageCode: "1f538" },
  { number: 98, block: "H", category: "Tiempo", romaji: "kyou", spanish: "hoy", imageCode: "1f4c5" },
  { number: 99, block: "H", category: "Tiempo", romaji: "ashita", spanish: "ma?ana", imageCode: "1f305" },
  { number: 100, block: "H", category: "Tiempo", romaji: "kinou", spanish: "ayer", imageCode: "23ea" },
  { number: 101, block: "H", category: "Tiempo", romaji: "ima", spanish: "ahora", imageCode: "23f0" },
  { number: 102, block: "H", category: "Tiempo", romaji: "ato", spanish: "despu?s", imageCode: "23ed" },
  { number: 103, block: "H", category: "Tiempo", romaji: "mae", spanish: "antes", imageCode: "23ee" },
  { number: 104, block: "H", category: "Tiempo", romaji: "asa", spanish: "ma?ana temprano", imageCode: "1f305" },
  { number: 105, block: "H", category: "Tiempo", romaji: "hiru", spanish: "tarde", imageCode: "1f31e" },
  { number: 106, block: "H", category: "Tiempo", romaji: "yoru", spanish: "noche", imageCode: "1f319" },
  { number: 107, block: "H", category: "Tiempo", romaji: "jikan", spanish: "tiempo", imageCode: "23f0" },
  { number: 108, block: "H", category: "Tiempo", romaji: "toki", spanish: "momento", imageCode: "23f1" },
  { number: 109, block: "H", category: "Tiempo", romaji: "raishuu", spanish: "pr?xima semana", imageCode: "1f4c6" },
  { number: 110, block: "I", category: "Preguntas poderosas", romaji: "nani", spanish: "qu?", imageCode: "2753" },
  { number: 111, block: "I", category: "Preguntas poderosas", romaji: "dare", spanish: "qui?n", imageCode: "1f464" },
  { number: 112, block: "I", category: "Preguntas poderosas", romaji: "doko", spanish: "d?nde", imageCode: "1f4cd" },
  { number: 113, block: "I", category: "Preguntas poderosas", romaji: "itsu", spanish: "cu?ndo", imageCode: "1f4c5" },
  { number: 114, block: "I", category: "Preguntas poderosas", romaji: "naze", spanish: "por qu?", imageCode: "1f914" },
  { number: 115, block: "I", category: "Preguntas poderosas", romaji: "dou", spanish: "c?mo", imageCode: "2699" },
  { number: 116, block: "I", category: "Preguntas poderosas", romaji: "dochira", spanish: "cu?l", imageCode: "1f500" },
  { number: 117, block: "I", category: "Preguntas poderosas", romaji: "donna", spanish: "qu? tipo", imageCode: "1f3f7" },
  { number: 118, block: "I", category: "Preguntas poderosas", romaji: "ikutsu", spanish: "cu?ntos", imageCode: "1f522" },
  { number: 119, block: "I", category: "Preguntas poderosas", romaji: "donna hito", spanish: "qu? tipo de persona", imageCode: "1f9d1" },
  { number: 120, block: "J", category: "Emociones", romaji: "ureshii", spanish: "feliz", imageCode: "1f604" },
  { number: 121, block: "J", category: "Emociones", romaji: "sabishii", spanish: "triste", imageCode: "1f622" },
  { number: 122, block: "J", category: "Emociones", romaji: "tanoshii", spanish: "divertido", imageCode: "1f389" },
  { number: 123, block: "J", category: "Emociones", romaji: "kowai", spanish: "miedo", imageCode: "1f631" },
  { number: 124, block: "J", category: "Emociones", romaji: "shinpai", spanish: "preocupaci?n", imageCode: "1f61f" },
  { number: 125, block: "J", category: "Emociones", romaji: "anshin", spanish: "tranquilidad", imageCode: "1f60c" },
  { number: 126, block: "J", category: "Emociones", romaji: "komaru", spanish: "problema", imageCode: "26a0" },
  { number: 127, block: "J", category: "Emociones", romaji: "okoru", spanish: "enojarse", imageCode: "1f620" },
  { number: 128, block: "J", category: "Emociones", romaji: "yorokobu", spanish: "alegrarse", imageCode: "1f60a" },
  { number: 129, block: "J", category: "Emociones", romaji: "warau", spanish: "re?r", imageCode: "1f606" },
  { number: 130, block: "J", category: "Emociones", romaji: "naku", spanish: "llorar", imageCode: "1f62d" },
  { number: 131, block: "K", category: "Relaciones y afecto", romaji: "ai", spanish: "amor", imageCode: "2764" },
  { number: 132, block: "K", category: "Relaciones y afecto", romaji: "koi", spanish: "enamoramiento", imageCode: "1f498" },
  { number: 133, block: "K", category: "Relaciones y afecto", romaji: "deeto", spanish: "cita", imageCode: "1f4c5" },
  { number: 134, block: "K", category: "Relaciones y afecto", romaji: "egao", spanish: "sonrisa", imageCode: "1f60a" },
  { number: 135, block: "K", category: "Relaciones y afecto", romaji: "kokoro", spanish: "coraz?n", imageCode: "2764" },
  { number: 136, block: "K", category: "Relaciones y afecto", romaji: "kimochi", spanish: "sentimiento", imageCode: "1f49f" },
  { number: 137, block: "K", category: "Relaciones y afecto", romaji: "shiawase", spanish: "felicidad", imageCode: "1f60a" },
  { number: 138, block: "K", category: "Relaciones y afecto", romaji: "yume", spanish: "sue?o", imageCode: "1f4ad" },
  { number: 139, block: "K", category: "Relaciones y afecto", romaji: "kibou", spanish: "esperanza", imageCode: "1f54a" },
  { number: 140, block: "K", category: "Relaciones y afecto", romaji: "yakusoku", spanish: "promesa", imageCode: "1f91d" },
  { number: 141, block: "K", category: "Relaciones y afecto", romaji: "himitsu", spanish: "secreto", imageCode: "1f92b" },
  { number: 142, block: "K", category: "Relaciones y afecto", romaji: "aishiteru", spanish: "te amo", imageCode: "1f970" },
  { number: 143, block: "L", category: "Gustos y entretenimiento", romaji: "suki", spanish: "gustar", imageCode: "1f44d" },
  { number: 144, block: "L", category: "Gustos y entretenimiento", romaji: "kirai", spanish: "no gustar", imageCode: "1f44e" },
  { number: 145, block: "L", category: "Gustos y entretenimiento", romaji: "ongaku", spanish: "m?sica", imageCode: "1f3b5" },
  { number: 146, block: "L", category: "Gustos y entretenimiento", romaji: "uta", spanish: "canci?n", imageCode: "1f3a4" },
  { number: 147, block: "L", category: "Gustos y entretenimiento", romaji: "piano", spanish: "piano", imageCode: "1f3b9" },
  { number: 148, block: "L", category: "Gustos y entretenimiento", romaji: "eiga", spanish: "pel?cula", imageCode: "1f3ac" },
  { number: 149, block: "L", category: "Gustos y entretenimiento", romaji: "hon", spanish: "libro", imageCode: "1f4d6" },
  { number: 150, block: "L", category: "Gustos y entretenimiento", romaji: "shashin", spanish: "foto", imageCode: "1f4f7" },
  { number: 151, block: "L", category: "Gustos y entretenimiento", romaji: "odoru", spanish: "bailar", imageCode: "1f483" },
  { number: 152, block: "L", category: "Gustos y entretenimiento", romaji: "asobu", spanish: "jugar", imageCode: "1f3ae" },
  { number: 153, block: "L", category: "Gustos y entretenimiento", romaji: "ryokou", spanish: "viaje", imageCode: "1f9f3" },
  { number: 154, block: "M", category: "Trabajo y estudio", romaji: "shigoto", spanish: "trabajo", imageCode: "1f4bc" },
  { number: 155, block: "M", category: "Trabajo y estudio", romaji: "kaigi", spanish: "reuni?n", imageCode: "1f465" },
  { number: 156, block: "M", category: "Trabajo y estudio", romaji: "mondai", spanish: "problema", imageCode: "26a0" },
  { number: 157, block: "M", category: "Trabajo y estudio", romaji: "keiken", spanish: "experiencia", imageCode: "1f9ed" },
  { number: 158, block: "M", category: "Trabajo y estudio", romaji: "chance", spanish: "oportunidad", imageCode: "1f513" },
  { number: 159, block: "M", category: "Trabajo y estudio", romaji: "seikou", spanish: "?xito", imageCode: "1f3c6" },
  { number: 160, block: "M", category: "Trabajo y estudio", romaji: "shippai", spanish: "fracaso", imageCode: "274c" },
  { number: 161, block: "M", category: "Trabajo y estudio", romaji: "benkyou", spanish: "estudio", imageCode: "1f4da" },
  { number: 162, block: "M", category: "Trabajo y estudio", romaji: "narau", spanish: "aprender", imageCode: "1f393" },
  { number: 163, block: "M", category: "Trabajo y estudio", romaji: "oshieru", spanish: "ense?ar", imageCode: "1f3eb" },
  { number: 164, block: "M", category: "Trabajo y estudio", romaji: "renshuu", spanish: "pr?ctica", imageCode: "270d" },
  { number: 165, block: "M", category: "Trabajo y estudio", romaji: "jouzu", spanish: "h?bil", imageCode: "1f3af" },
  { number: 166, block: "N", category: "Adjetivos clave (1)", romaji: "kirei", spanish: "bonito", imageCode: "2728" },
  { number: 167, block: "N", category: "Adjetivos clave (1)", romaji: "kawaii", spanish: "lindo", imageCode: "1f970" },
  { number: 168, block: "N", category: "Adjetivos clave (1)", romaji: "kakkoii", spanish: "atractivo", imageCode: "1f60e" },
  { number: 169, block: "N", category: "Adjetivos clave (1)", romaji: "suteki", spanish: "encantador", imageCode: "1f496" },
  { number: 170, block: "N", category: "Adjetivos clave (1)", romaji: "ookii", spanish: "grande", imageCode: "1f418" },
  { number: 171, block: "N", category: "Adjetivos clave (1)", romaji: "chiisai", spanish: "peque?o", imageCode: "1f41c" },
  { number: 172, block: "N", category: "Adjetivos clave (1)", romaji: "atarashii", spanish: "nuevo", imageCode: "1f195" },
  { number: 173, block: "N", category: "Adjetivos clave (1)", romaji: "furui", spanish: "viejo", imageCode: "1f3da" },
  { number: 174, block: "N", category: "Adjetivos clave (1)", romaji: "muzukashii", spanish: "dif?cil", imageCode: "1f9e9" },
  { number: 175, block: "N", category: "Adjetivos clave (1)", romaji: "kantan", spanish: "f?cil", imageCode: "2705" },
  { number: 176, block: "N", category: "Adjetivos clave (1)", romaji: "sugoi", spanish: "incre?ble", imageCode: "1f929" },
  { number: 177, block: "N", category: "Adjetivos clave (1)", romaji: "benri", spanish: "conveniente", imageCode: "1f527" },
  { number: 178, block: "N", category: "Adjetivos clave (1)", romaji: "taihen", spanish: "complicado", imageCode: "1f635" },
  { number: 179, block: "N", category: "Adjetivos clave (1)", romaji: "hen", spanish: "raro", imageCode: "1f928" },
  { number: 180, block: "N", category: "Adjetivos clave (1)", romaji: "akarui", spanish: "alegre / brillante", imageCode: "1f31e" },
  { number: 181, block: "N", category: "Adjetivos clave (1)", romaji: "kurai", spanish: "oscuro / triste", imageCode: "1f311" },
  { number: 182, block: "N", category: "Adjetivos clave (1)", romaji: "shizuka", spanish: "tranquilo", imageCode: "1f92b" },
  { number: 183, block: "N", category: "Adjetivos clave (1)", romaji: "urusai", spanish: "ruidoso", imageCode: "1f50a" },
  { number: 184, block: "N", category: "Adjetivos clave (1)", romaji: "nigiyaka", spanish: "animado", imageCode: "1f389" },
  { number: 185, block: "N", category: "Adjetivos clave (1)", romaji: "omoi", spanish: "pesado", imageCode: "1f4aa" },
  { number: 186, block: "N", category: "Adjetivos clave (1)", romaji: "karui", spanish: "ligero", imageCode: "1f388" },
  { number: 187, block: "N", category: "Adjetivos clave (1)", romaji: "nagai", spanish: "largo", imageCode: "1f4cf" },
  { number: 188, block: "N", category: "Adjetivos clave (1)", romaji: "mijikai", spanish: "corto", imageCode: "2702" },
  { number: 189, block: "N", category: "Adjetivos clave (1)", romaji: "anzen", spanish: "seguro", imageCode: "1f6e1" },
  { number: 190, block: "N", category: "Adjetivos clave (1)", romaji: "abunai", spanish: "peligroso", imageCode: "26a0" },
  { number: 191, block: "N", category: "Adjetivos clave (1)", romaji: "majime", spanish: "serio", imageCode: "1f9d1" },
  { number: 192, block: "N", category: "Adjetivos clave (1)", romaji: "yasashii", spanish: "amable", imageCode: "1f917" },
  { number: 193, block: "N", category: "Adjetivos clave (1)", romaji: "shinsetsu", spanish: "gentil", imageCode: "1f49a" },
  { number: 194, block: "N", category: "Adjetivos clave (1)", romaji: "kibishii", spanish: "estricto", imageCode: "1f6a8" },
  { number: 195, block: "N", category: "Adjetivos clave (1)", romaji: "tokubetsu", spanish: "especial", imageCode: "2b50" },
  { number: 196, block: "N", category: "Adjetivos clave (1)", romaji: "taisetsu", spanish: "importante", imageCode: "1f48e" },
  { number: 197, block: "N", category: "Adjetivos clave (1)", romaji: "utsukushii", spanish: "hermoso", imageCode: "1f338" },
  { number: 198, block: "O", category: "Naturaleza y mundo", romaji: "yama", spanish: "monta?a", imageCode: "26f0" },
  { number: 199, block: "O", category: "Naturaleza y mundo", romaji: "umi", spanish: "mar", imageCode: "1f30a" },
  { number: 200, block: "O", category: "Naturaleza y mundo", romaji: "sora", spanish: "cielo", imageCode: "2601" },
  { number: 201, block: "O", category: "Naturaleza y mundo", romaji: "ame", spanish: "lluvia", imageCode: "1f327" },
  { number: 202, block: "O", category: "Naturaleza y mundo", romaji: "taiyou", spanish: "sol", imageCode: "2600" },
  { number: 203, block: "O", category: "Naturaleza y mundo", romaji: "tsuki", spanish: "luna", imageCode: "1f319" },
  { number: 204, block: "O", category: "Naturaleza y mundo", romaji: "hoshi", spanish: "estrella", imageCode: "2b50" },
  { number: 205, block: "O", category: "Naturaleza y mundo", romaji: "kaze", spanish: "viento", imageCode: "1f32c" },
  { number: 206, block: "O", category: "Naturaleza y mundo", romaji: "hana", spanish: "flor", imageCode: "1f33c" },
  { number: 207, block: "O", category: "Naturaleza y mundo", romaji: "ki", spanish: "?rbol", imageCode: "1f333" },
  { number: 208, block: "O", category: "Naturaleza y mundo", romaji: "hi", spanish: "fuego", imageCode: "1f525" },
  { number: 209, block: "O", category: "Naturaleza y mundo", romaji: "tsuchi", spanish: "tierra", imageCode: "1f30d" },
  { number: 210, block: "P", category: "Animales", romaji: "inu", spanish: "perro", imageCode: "1f436" },
  { number: 211, block: "P", category: "Animales", romaji: "neko", spanish: "gato", imageCode: "1f431" },
  { number: 212, block: "P", category: "Animales", romaji: "tori", spanish: "p?jaro", imageCode: "1f426" },
  { number: 213, block: "P", category: "Animales", romaji: "sakana", spanish: "pez", imageCode: "1f41f" },
  { number: 214, block: "P", category: "Animales", romaji: "uma", spanish: "caballo", imageCode: "1f434" },
  { number: 215, block: "P", category: "Animales", romaji: "usagi", spanish: "conejo", imageCode: "1f430" },
  { number: 216, block: "Q", category: "Movimiento social", romaji: "au", spanish: "encontrarse", imageCode: "1f91d" },
  { number: 217, block: "Q", category: "Movimiento social", romaji: "wakareru", spanish: "separarse", imageCode: "1f44b" },
  { number: 218, block: "Q", category: "Movimiento social", romaji: "ageru", spanish: "dar", imageCode: "1f381" },
  { number: 219, block: "Q", category: "Movimiento social", romaji: "morau", spanish: "recibir", imageCode: "1f4e5" },
  { number: 220, block: "Q", category: "Movimiento social", romaji: "kureru", spanish: "darme", imageCode: "1f64f" },
  { number: 221, block: "Q", category: "Movimiento social", romaji: "ikou", spanish: "vamos", imageCode: "1f449" },
  { number: 222, block: "Q", category: "Movimiento social", romaji: "kaette", spanish: "vuelve", imageCode: "1f504" },
  { number: 223, block: "Q", category: "Movimiento social", romaji: "aitai", spanish: "quiero verte", imageCode: "1f440" },
  { number: 224, block: "Q", category: "Movimiento social", romaji: "shinjiru", spanish: "confiar", imageCode: "1f91d" },
  { number: 225, block: "Q", category: "Movimiento social", romaji: "tasukaru", spanish: "recibir ayuda", imageCode: "1f198" },
  { number: 226, block: "R", category: "Expresiones frecuentes", romaji: "zettai", spanish: "definitivamente", imageCode: "2705" },
  { number: 227, block: "R", category: "Expresiones frecuentes", romaji: "mada", spanish: "todav?a", imageCode: "23f3" },
  { number: 228, block: "R", category: "Expresiones frecuentes", romaji: "mou", spanish: "ya", imageCode: "2705" },
  { number: 229, block: "R", category: "Expresiones frecuentes", romaji: "zenzen", spanish: "para nada", imageCode: "1f6ab" },
  { number: 230, block: "R", category: "Expresiones frecuentes", romaji: "itsumo", spanish: "siempre", imageCode: "267e" },
  { number: 231, block: "R", category: "Expresiones frecuentes", romaji: "tokidoki", spanish: "a veces", imageCode: "1f501" },
  { number: 232, block: "R", category: "Expresiones frecuentes", romaji: "amari", spanish: "no mucho", imageCode: "1f538" },
  { number: 233, block: "R", category: "Expresiones frecuentes", romaji: "zenbu", spanish: "todo", imageCode: "1f30d" },
  { number: 234, block: "R", category: "Expresiones frecuentes", romaji: "minna", spanish: "todos", imageCode: "1f465" },
  { number: 235, block: "R", category: "Expresiones frecuentes", romaji: "kondo", spanish: "pr?xima vez", imageCode: "1f4c6" },
  { number: 236, block: "R", category: "Expresiones frecuentes", romaji: "saigo", spanish: "final", imageCode: "1f3c1" },
  { number: 237, block: "R", category: "Expresiones frecuentes", romaji: "hajime", spanish: "comienzo", imageCode: "1f530" },
  { number: 238, block: "S", category: "Vida social", romaji: "hima", spanish: "tiempo libre", imageCode: "1f3d6" },
  { number: 239, block: "S", category: "Vida social", romaji: "kyuujitsu", spanish: "d?a libre", imageCode: "1f3dd" },
  { number: 240, block: "S", category: "Vida social", romaji: "shuumatsu", spanish: "fin de semana", imageCode: "1f5d3" },
  { number: 241, block: "S", category: "Vida social", romaji: "tanjoubi", spanish: "cumplea?os", imageCode: "1f382" },
  { number: 242, block: "S", category: "Vida social", romaji: "omatsuri", spanish: "festival", imageCode: "1f38f" },
  { number: 243, block: "S", category: "Vida social", romaji: "paatii", spanish: "fiesta", imageCode: "1f389" },
  { number: 244, block: "S", category: "Vida social", romaji: "konban", spanish: "esta noche", imageCode: "1f303" },
  { number: 245, block: "S", category: "Vida social", romaji: "kesa", spanish: "esta ma?ana", imageCode: "1f305" },
  { number: 246, block: "S", category: "Vida social", romaji: "mayoi", spanish: "perdido", imageCode: "1f9ed" },
  { number: 247, block: "S", category: "Vida social", romaji: "denwa", spanish: "llamada", imageCode: "1f4de" },
  { number: 248, block: "T", category: "Acciones extra", romaji: "miru", spanish: "ver", imageCode: "1f440" },
  { number: 249, block: "T", category: "Acciones extra", romaji: "yomu", spanish: "leer", imageCode: "1f4d6" },
  { number: 250, block: "T", category: "Acciones extra", romaji: "noru", spanish: "subir / montar", imageCode: "1f68c" },
  { number: 251, block: "T", category: "Acciones extra", romaji: "oriru", spanish: "bajar", imageCode: "1f53d" },
  { number: 252, block: "T", category: "Acciones extra", romaji: "okiru", spanish: "despertar", imageCode: "23f0" },
  { number: 253, block: "T", category: "Acciones extra", romaji: "nareru", spanish: "acostumbrarse", imageCode: "1f501" },
  { number: 254, block: "T", category: "Acciones extra", romaji: "hajimaru", spanish: "empezar", imageCode: "25b6" },
  { number: 255, block: "T", category: "Acciones extra", romaji: "owaru", spanish: "terminar", imageCode: "1f3c1" },
  { number: 256, block: "T", category: "Acciones extra", romaji: "tsuzuku", spanish: "continuar", imageCode: "27a1" },
  { number: 257, block: "T", category: "Acciones extra", romaji: "yoroshiku", spanish: "buen trato / encantado", imageCode: "1f91d" },
  { number: 258, block: "U", category: "Transporte y movimiento", romaji: "densha", spanish: "tren", imageCode: "1f686" },
  { number: 259, block: "U", category: "Transporte y movimiento", romaji: "basu", spanish: "bus", imageCode: "1f68c" },
  { number: 260, block: "U", category: "Transporte y movimiento", romaji: "kuruma", spanish: "carro", imageCode: "1f697" },
  { number: 261, block: "U", category: "Transporte y movimiento", romaji: "jitensha", spanish: "bicicleta", imageCode: "1f6b2" },
  { number: 262, block: "U", category: "Transporte y movimiento", romaji: "hikouki", spanish: "avi?n", imageCode: "2708" },
  { number: 263, block: "U", category: "Transporte y movimiento", romaji: "taxi", spanish: "taxi", imageCode: "1f695" },
  { number: 264, block: "U", category: "Transporte y movimiento", romaji: "michi", spanish: "calle / camino", imageCode: "1f6e3" },
  { number: 265, block: "U", category: "Transporte y movimiento", romaji: "chikaku", spanish: "cerca", imageCode: "1f4cd" },
  { number: 266, block: "U", category: "Transporte y movimiento", romaji: "tooi", spanish: "lejos", imageCode: "1f5fa" },
  { number: 267, block: "U", category: "Transporte y movimiento", romaji: "hayai", spanish: "r?pido / temprano", imageCode: "1f3c3" },
  { number: 268, block: "U", category: "Transporte y movimiento", romaji: "osoi", spanish: "lento / tarde", imageCode: "1f422" },
  { number: 269, block: "V", category: "Casa y objetos diarios", romaji: "kaban", spanish: "bolso", imageCode: "1f45c" },
  { number: 270, block: "V", category: "Casa y objetos diarios", romaji: "kagi", spanish: "llave", imageCode: "1f511" },
  { number: 271, block: "V", category: "Casa y objetos diarios", romaji: "kasa", spanish: "paraguas", imageCode: "2602" },
  { number: 272, block: "V", category: "Casa y objetos diarios", romaji: "kutsu", spanish: "zapatos", imageCode: "1f45f" },
  { number: 273, block: "V", category: "Casa y objetos diarios", romaji: "fuku", spanish: "ropa", imageCode: "1f455" },
  { number: 274, block: "V", category: "Casa y objetos diarios", romaji: "isu", spanish: "silla", imageCode: "1f4ba" },
  { number: 275, block: "V", category: "Casa y objetos diarios", romaji: "tsukue", spanish: "mesa / escritorio", imageCode: "1f4bb" },
  { number: 276, block: "V", category: "Casa y objetos diarios", romaji: "doa", spanish: "puerta", imageCode: "1f6aa" },
  { number: 277, block: "V", category: "Casa y objetos diarios", romaji: "mado", spanish: "ventana", imageCode: "1fa9f" },
  { number: 278, block: "V", category: "Casa y objetos diarios", romaji: "heya", spanish: "habitaci?n", imageCode: "1f6cf" },
  { number: 279, block: "W", category: "Tecnolog?a y vida moderna", romaji: "wi-fi", spanish: "wifi", imageCode: "1f4f6" },
  { number: 280, block: "W", category: "Tecnolog?a y vida moderna", romaji: "pasokon", spanish: "computador", imageCode: "1f4bb" },
  { number: 281, block: "W", category: "Tecnolog?a y vida moderna", romaji: "apuri", spanish: "aplicaci?n", imageCode: "1f4f1" },
  { number: 282, block: "W", category: "Tecnolog?a y vida moderna", romaji: "kamera", spanish: "c?mara", imageCode: "1f4f7" },
  { number: 283, block: "W", category: "Tecnolog?a y vida moderna", romaji: "terebi", spanish: "televisi?n", imageCode: "1f4fa" },
  { number: 284, block: "W", category: "Tecnolog?a y vida moderna", romaji: "rajio", spanish: "radio", imageCode: "1f4fb" },
  { number: 285, block: "W", category: "Tecnolog?a y vida moderna", romaji: "denchi", spanish: "bater?a", imageCode: "1f50b" },
  { number: 286, block: "W", category: "Tecnolog?a y vida moderna", romaji: "juuden", spanish: "cargar bater?a", imageCode: "1f50c" },
  { number: 287, block: "X", category: "Salud y emergencia", romaji: "itai", spanish: "dolor", imageCode: "1f915" },
  { number: 288, block: "X", category: "Salud y emergencia", romaji: "daijoubu", spanish: "estar bien", imageCode: "2705" },
  { number: 289, block: "X", category: "Salud y emergencia", romaji: "kusuri", spanish: "medicina", imageCode: "1f48a" },
  { number: 290, block: "X", category: "Salud y emergencia", romaji: "byouki", spanish: "enfermedad", imageCode: "1f912" },
  { number: 291, block: "X", category: "Salud y emergencia", romaji: "jiko", spanish: "accidente", imageCode: "1f6a8" },
  { number: 292, block: "X", category: "Salud y emergencia", romaji: "keisatsu", spanish: "polic?a", imageCode: "1f693" },
  { number: 293, block: "X", category: "Salud y emergencia", romaji: "tasukete", spanish: "ay?dame", imageCode: "1f198" },
  { number: 294, block: "X", category: "Salud y emergencia", romaji: "abunai", spanish: "peligroso", imageCode: "26a0" },
  { number: 295, block: "X", category: "Salud y emergencia", romaji: "anzen", spanish: "seguro", imageCode: "1f6e1" },
  { number: 296, block: "Y", category: "Fuerza interior", romaji: "jiyuu", spanish: "libertad", imageCode: "1f54a" },
  { number: 297, block: "Y", category: "Fuerza interior", romaji: "chikara", spanish: "fuerza", imageCode: "1f4aa" },
  { number: 298, block: "Y", category: "Fuerza interior", romaji: "yuuki", spanish: "valent?a", imageCode: "1f981" },
  { number: 299, block: "Y", category: "Fuerza interior", romaji: "genjitsu", spanish: "realidad", imageCode: "1f441" },
  { number: 300, block: "Y", category: "Fuerza interior", romaji: "mirai", spanish: "futuro", imageCode: "1f52e" },
] satisfies StarterJaEsEntry[];

function getStarterCardId(number: number): string {
  return `00000000-0000-4000-8000-${String(number).padStart(12, "0")}`;
}

function getCreatedAt(number: number): string {
  return new Date(Date.UTC(2026, 0, 1, 0, 0, number)).toISOString();
}

function getImageUrl(imageCode: string): string {
  return `${TWEMOJI_BASE_URL}/${imageCode}.svg`;
}

export const starterJaEsCards: VocabularyCard[] = starterJaEsEntries.map((entry) => ({
  id: getStarterCardId(entry.number),
  type: "word",
  isStarter: true,
  learningMode: "ja_es",
  learningLanguage: "ja",
  supportLanguage: "es",
  learningText: entry.romaji,
  supportText: entry.spanish,
  japaneseRomaji: entry.romaji,
  spanish: entry.spanish,
  category: `Bloque ${entry.block} - ${entry.category}`,
  imageUrl: getImageUrl(entry.imageCode),
  createdAt: getCreatedAt(entry.number),
}));
