import {
  getJjuKoEsStarterCardId,
  getStarterCreatedAt,
  getStarterImageUrl,
} from "@/lib/starter-vocabulary";
import type { CardType, VocabularyCard } from "@/types/card";

interface StarterJjuEntry {
  type: CardType;
  category: string;
  spanish: string;
  korean: string;
  koreanReading: string;
  imageCode: string;
}

export const starterJjuKoEsEntries = [
  { type: "word", category: "Jju verbos", spanish: "hacer", korean: "하다", koreanReading: "hada", imageCode: "1f6e0" },
  { type: "phrase", category: "Jju verbos", spanish: "Hace frío.", korean: "추워요.", koreanReading: "chuwoyo", imageCode: "2744" },
  { type: "word", category: "Jju verbos", spanish: "usar", korean: "사용하다", koreanReading: "sayonghada", imageCode: "1f527" },
  { type: "phrase", category: "Jju verbos", spanish: "Uso un vestido.", korean: "저는 원피스를 입어요.", koreanReading: "jeoneun wonpiseureul ibeoyo", imageCode: "1f457" },
  { type: "word", category: "Jju verbos", spanish: "hablar", korean: "말하다", koreanReading: "malhada", imageCode: "1f5e3" },
  { type: "phrase", category: "Jju verbos", spanish: "Hablo un poco de español.", korean: "저는 스페인어를 조금 말해요.", koreanReading: "jeoneun seupeineoreul jogeum malhaeyo", imageCode: "1f5e3" },
  { type: "word", category: "Jju verbos", spanish: "querer", korean: "원하다", koreanReading: "wonhada", imageCode: "1f496" },
  { type: "phrase", category: "Jju verbos", spanish: "¡Quiero un helado!", korean: "아이스크림 하나 먹고 싶어요!", koreanReading: "aiseukeurim hana meokgo sipeoyo", imageCode: "1f368" },
  { type: "word", category: "Jju verbos", spanish: "necesitar", korean: "필요하다", koreanReading: "piryohada", imageCode: "1f6df" },
  { type: "phrase", category: "Jju verbos", spanish: "Necesito un amigo.", korean: "저는 친구가 필요해요.", koreanReading: "jeoneun chinguga piryohaeyo", imageCode: "1f91d" },
  { type: "word", category: "Jju verbos", spanish: "cantar", korean: "노래하다", koreanReading: "noraehada", imageCode: "1f3a4" },
  { type: "phrase", category: "Jju verbos", spanish: "Canto mi canción favorita.", korean: "저는 제가 가장 좋아하는 노래를 불러요.", koreanReading: "jeoneun jega gajang joahaneun noraereul bulleoyo", imageCode: "1f3b5" },
  { type: "word", category: "Jju verbos", spanish: "bailar", korean: "춤추다", koreanReading: "chumchuda", imageCode: "1f483" },
  { type: "phrase", category: "Jju verbos", spanish: "Baila salsa.", korean: "그는 살사를 춰요.", koreanReading: "geuneun salsareul chwoyo", imageCode: "1f483" },
  { type: "word", category: "Jju verbos", spanish: "escuchar", korean: "듣다", koreanReading: "deutda", imageCode: "1f442" },
  { type: "phrase", category: "Jju verbos", spanish: "Escucha música.", korean: "음악을 들어요.", koreanReading: "eumageul deureoyo", imageCode: "1f3b5" },
  { type: "word", category: "Jju verbos", spanish: "mirar", korean: "보다", koreanReading: "boda", imageCode: "1f440" },
  { type: "phrase", category: "Jju verbos", spanish: "Miro una película.", korean: "저는 영화를 봐요.", koreanReading: "jeoneun yeonghwareul bwayo", imageCode: "1f3ac" },
  { type: "word", category: "Jju verbos", spanish: "pintar", korean: "그리다", koreanReading: "geurida", imageCode: "1f3a8" },
  { type: "phrase", category: "Jju verbos", spanish: "Pinta a menudo.", korean: "자주 그림을 그려요.", koreanReading: "jaju geurimeul geuryeoyo", imageCode: "1f3a8" },
  { type: "word", category: "Jju verbos", spanish: "viajar", korean: "여행하다", koreanReading: "yeohaenghada", imageCode: "1f9f3" },
  { type: "phrase", category: "Jju verbos", spanish: "Viaja mucho.", korean: "그는 여행을 많이 해요.", koreanReading: "geuneun yeohaengeul mani haeyo", imageCode: "1f9f3" },
  { type: "word", category: "Jju verbos", spanish: "cocinar", korean: "요리하다", koreanReading: "yorihada", imageCode: "1f373" },
  { type: "phrase", category: "Jju verbos", spanish: "Cocino arroz con pollo.", korean: "저는 닭고기밥을 요리해요.", koreanReading: "jeoneun dakgogibabeul yorihaeyo", imageCode: "1f35a" },
  { type: "word", category: "Jju verbos", spanish: "mandar", korean: "보내다", koreanReading: "bonaeda", imageCode: "1f4e9" },
  { type: "phrase", category: "Jju verbos", spanish: "Mando un mensaje.", korean: "저는 메시지를 보내요.", koreanReading: "jeoneun mesajireul bonaeyo", imageCode: "1f4e9" },
  { type: "word", category: "Jju verbos", spanish: "entrenar", korean: "훈련하다", koreanReading: "hullyeonhada", imageCode: "1f3cb" },
  { type: "phrase", category: "Jju verbos", spanish: "Entrena con un entrenador.", korean: "트레이너와 함께 훈련해요.", koreanReading: "teureineowa hamkke hullyeonhaeyo", imageCode: "1f3cb" },
  { type: "word", category: "Jju verbos", spanish: "nadar", korean: "수영하다", koreanReading: "suyeonghada", imageCode: "1f3ca" },
  { type: "phrase", category: "Jju verbos", spanish: "Nada en la piscina.", korean: "수영장에서 수영해요.", koreanReading: "suyeongjangeseo suyeonghaeyo", imageCode: "1f3ca" },
  { type: "word", category: "Jju verbos", spanish: "caminar", korean: "걷다", koreanReading: "geotda", imageCode: "1f6b6" },
  { type: "word", category: "Jju verbos", spanish: "pasear", korean: "산책하다", koreanReading: "sanchaekhada", imageCode: "1f6b6" },
  { type: "phrase", category: "Jju verbos", spanish: "Camino mucho porque mi casa está lejos.", korean: "집이 멀어서 많이 걸어요.", koreanReading: "jibi meoreoseo mani georeoyo", imageCode: "1f6b6" },
  { type: "word", category: "Jju verbos", spanish: "esquiar", korean: "스키를 타다", koreanReading: "seukireul tada", imageCode: "26f7" },
  { type: "phrase", category: "Jju verbos", spanish: "Siempre esquío con equipo.", korean: "저는 항상 장비를 갖추고 스키를 타요.", koreanReading: "jeoneun hangsang jangbireul gatchugo seukireul tayo", imageCode: "26f7" },
  { type: "phrase", category: "Jju verbos", spanish: "levantar pesas", korean: "역기를 들다", koreanReading: "yeokkireul deulda", imageCode: "1f3cb" },
  { type: "word", category: "Jju verbos", spanish: "patinar", korean: "스케이트를 타다", koreanReading: "seukeiteureul tada", imageCode: "26f8" },
  { type: "word", category: "Jju verbos", spanish: "dibujar", korean: "그림을 그리다", koreanReading: "geurimeul geurida", imageCode: "270f" },
  { type: "word", category: "Jju verbos", spanish: "pescar", korean: "낚시하다", koreanReading: "naksihada", imageCode: "1f3a3" },
  { type: "phrase", category: "Jju verbos", spanish: "Pescamos.", korean: "우리는 낚시해요.", koreanReading: "urineun naksihaeyo", imageCode: "1f3a3" },
  { type: "word", category: "Jju verbos", spanish: "enseñar", korean: "가르치다", koreanReading: "gareuchida", imageCode: "1f3eb" },
  { type: "phrase", category: "Jju verbos", spanish: "¿Me puedes enseñar español?", korean: "저에게 스페인어를 가르쳐 줄 수 있어요?", koreanReading: "jeoege seupeineoreul gareuchyeo jul su isseoyo", imageCode: "1f3eb" },
  { type: "phrase", category: "Jju verbos", spanish: "Enséñame español.", korean: "나에게 스페인어를 가르쳐 줘.", koreanReading: "naege seupeineoreul gareuchyeo jwo", imageCode: "1f3eb" },
  { type: "word", category: "Jju verbos", spanish: "aprender", korean: "배우다", koreanReading: "baeuda", imageCode: "1f393" },
  { type: "phrase", category: "Jju verbos", spanish: "Estoy aprendiendo español.", korean: "저는 스페인어를 배우고 있어요.", koreanReading: "jeoneun seupeineoreul baeugo isseoyo", imageCode: "1f393" },
  { type: "word", category: "Jju verbos", spanish: "pasar", korean: "일어나다 / 지나가다", koreanReading: "ireonada / jinagada", imageCode: "1f504" },
  { type: "phrase", category: "Jju verbos", spanish: "¿Qué pasa?", korean: "무슨 일이야?", koreanReading: "museun iriya", imageCode: "2753" },
  { type: "phrase", category: "Jju verbos", spanish: "No pasa nada.", korean: "아무 일도 아니야.", koreanReading: "amu ildo aniya", imageCode: "2705" },
  { type: "phrase", category: "Jju verbos", spanish: "¿Qué te pasa?", korean: "너 왜 그래?", koreanReading: "neo wae geurae", imageCode: "2753" },
  { type: "phrase", category: "Jju verbos", spanish: "Me pasa mucho.", korean: "그런 일이 저에게 자주 일어나요.", koreanReading: "geureon iri jeoege jaju ireonayo", imageCode: "1f501" },
  { type: "phrase", category: "Jju verbos", spanish: "No sé qué me pasa.", korean: "저에게 무슨 일이 있는지 모르겠어요.", koreanReading: "jeoege museun iri inneunji moreugesseoyo", imageCode: "1f914" },
  { type: "word", category: "Jju verbos", spanish: "empezar", korean: "시작하다", koreanReading: "sijakhada", imageCode: "25b6" },
  { type: "phrase", category: "Jju verbos", spanish: "Empieza.", korean: "시작해요.", koreanReading: "sijakhaeyo", imageCode: "25b6" },
  { type: "word", category: "Jju verbos", spanish: "dormir", korean: "자다", koreanReading: "jada", imageCode: "1f6cc" },
  { type: "phrase", category: "Jju verbos", spanish: "Duermo ocho horas cada día.", korean: "저는 매일 여덟 시간 자요.", koreanReading: "jeoneun maeil yeodeol sigan jayo", imageCode: "1f6cc" },
  { type: "word", category: "Jju verbos", spanish: "repasar", korean: "복습하다", koreanReading: "boksseuphada", imageCode: "1f4d6" },
  { type: "phrase", category: "Jju verbos", spanish: "Repaso la lección.", korean: "저는 수업 내용을 복습해요.", koreanReading: "jeoneun sueop naeyongeul boksseuphaeyo", imageCode: "1f4d6" },
  { type: "word", category: "Jju verbos", spanish: "llevar", korean: "가지고 가다 / 입다", koreanReading: "gajigo gada / ipda", imageCode: "1f45c" },
  { type: "word", category: "Jju verbos", spanish: "buscar", korean: "찾다", koreanReading: "chatda", imageCode: "1f50d" },
  { type: "word", category: "Jju verbos", spanish: "mostrar", korean: "보여 주다", koreanReading: "boyeo juda", imageCode: "1f441" },
  { type: "phrase", category: "Jju verbos", spanish: "Muéstrame.", korean: "나에게 보여 줘.", koreanReading: "naege boyeo jwo", imageCode: "1f441" },
  { type: "phrase", category: "Jju verbos", spanish: "¿Me enseñas?", korean: "나에게 보여 줄래?", koreanReading: "naege boyeo jullae", imageCode: "1f441" },
  { type: "word", category: "Jju verbos", spanish: "tirar", korean: "던지다 / 버리다", koreanReading: "deonjida / beorida", imageCode: "1f5d1" },
  { type: "word", category: "Jju verbos", spanish: "dar", korean: "주다", koreanReading: "juda", imageCode: "1f381" },
  { type: "word", category: "Jju verbos", spanish: "darte", korean: "너에게 주다", koreanReading: "neoege juda", imageCode: "1f381" },
  { type: "word", category: "Jju verbos", spanish: "esperar", korean: "기다리다", koreanReading: "gidarida", imageCode: "23f3" },
  { type: "phrase", category: "Jju verbos", spanish: "Espere aquí.", korean: "여기서 기다리세요.", koreanReading: "yeogiseo gidariseyo", imageCode: "23f3" },
  { type: "word", category: "Jju verbos básicos", spanish: "ser", korean: "이다", koreanReading: "ida", imageCode: "1f464" },
  { type: "word", category: "Jju verbos básicos", spanish: "estar", korean: "있다 / 상태이다", koreanReading: "itda / sangtaeida", imageCode: "1f4cd" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "Está aquí.", korean: "여기에 있어요.", koreanReading: "yeogie isseoyo", imageCode: "1f4cd" },
  { type: "word", category: "Jju verbos básicos", spanish: "tener", korean: "가지다", koreanReading: "gajida", imageCode: "1f91a" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "Tienes razón.", korean: "네 말이 맞아.", koreanReading: "ne mari maja", imageCode: "2705" },
  { type: "word", category: "Jju verbos básicos", spanish: "poder", korean: "할 수 있다", koreanReading: "hal su itda", imageCode: "1f4aa" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "Puedo hablar.", korean: "저는 말할 수 있어요.", koreanReading: "jeoneun malhal su isseoyo", imageCode: "1f5e3" },
  { type: "word", category: "Jju verbos básicos", spanish: "ir", korean: "가다", koreanReading: "gada", imageCode: "1f6b6" },
  { type: "word", category: "Jju verbos básicos", spanish: "decir", korean: "말하다", koreanReading: "malhada", imageCode: "1f4ac" },
  { type: "word", category: "Jju verbos básicos", spanish: "ver", korean: "보다", koreanReading: "boda", imageCode: "1f440" },
  { type: "word", category: "Jju verbos básicos", spanish: "salir", korean: "나가다", koreanReading: "nagada", imageCode: "1f6aa" },
  { type: "word", category: "Jju verbos básicos", spanish: "venir", korean: "오다", koreanReading: "oda", imageCode: "1f44b" },
  { type: "word", category: "Jju verbos básicos", spanish: "llegar", korean: "도착하다", koreanReading: "dochakhada", imageCode: "1f3c1" },
  { type: "word", category: "Jju verbos básicos", spanish: "llamar", korean: "부르다 / 전화하다", koreanReading: "bureuda / jeonhwahada", imageCode: "1f4de" },
  { type: "word", category: "Jju verbos básicos", spanish: "gustar", korean: "좋아하다", koreanReading: "joahada", imageCode: "1f44d" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "Me gusta.", korean: "저는 좋아해요.", koreanReading: "jeoneun joahaeyo", imageCode: "1f44d" },
  { type: "word", category: "Jju verbos básicos", spanish: "saber", korean: "알다", koreanReading: "alda", imageCode: "1f4a1" },
  { type: "word", category: "Jju verbos básicos", spanish: "conocer", korean: "알다 / 만나다", koreanReading: "alda / mannada", imageCode: "1f91d" },
  { type: "word", category: "Jju verbos básicos", spanish: "trabajar", korean: "일하다", koreanReading: "ilhada", imageCode: "1f4bc" },
  { type: "word", category: "Jju verbos básicos", spanish: "comer", korean: "먹다", koreanReading: "meokda", imageCode: "1f374" },
  { type: "word", category: "Jju verbos básicos", spanish: "beber", korean: "마시다", koreanReading: "masida", imageCode: "1f964" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "Bebe.", korean: "마셔요.", koreanReading: "masyeoyo", imageCode: "1f964" },
  { type: "word", category: "Jju verbos básicos", spanish: "encontrar", korean: "찾다", koreanReading: "chatda", imageCode: "1f50d" },
  { type: "word", category: "Jju verbos básicos", spanish: "entender", korean: "이해하다", koreanReading: "ihaehada", imageCode: "1f4a1" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "Quiero entender.", korean: "이해하고 싶어요.", koreanReading: "ihaehago sipeoyo", imageCode: "1f4a1" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "No lo entiendo.", korean: "이해가 안 돼요.", koreanReading: "ihaega an dwaeyo", imageCode: "2753" },
  { type: "word", category: "Jju verbos básicos", spanish: "comprender", korean: "이해하다", koreanReading: "ihaehada", imageCode: "1f4a1" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "No comprendo la razón.", korean: "그 이유를 이해하지 못해요.", koreanReading: "geu iyureul ihaehaji motaeyo", imageCode: "2753" },
  { type: "word", category: "Jju verbos básicos", spanish: "pensar", korean: "생각하다", koreanReading: "saenggakhada", imageCode: "1f914" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "Yo pienso.", korean: "저는 생각해요.", koreanReading: "jeoneun saenggakhaeyo", imageCode: "1f914" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "Tú piensas.", korean: "너는 생각해.", koreanReading: "neoneun saenggakhae", imageCode: "1f914" },
  { type: "phrase", category: "Jju verbos básicos", spanish: "Estaba pensando en comer.", korean: "먹을까 생각하고 있었어요.", koreanReading: "meogeulkka saenggakhago isseosseoyo", imageCode: "1f374" },
  { type: "phrase", category: "Jju frases útiles", spanish: "Te extraño.", korean: "네가 보고 싶어.", koreanReading: "nega bogo sipeo", imageCode: "1f49c" },
  { type: "phrase", category: "Jju frases útiles", spanish: "¡Qué delicia!", korean: "정말 맛있다!", koreanReading: "jeongmal masitda", imageCode: "1f60b" },
  { type: "phrase", category: "Jju frases útiles", spanish: "Te deseo.", korean: "나는 너를 원해.", koreanReading: "naneun neoreul wonhae", imageCode: "1f496" },
  { type: "phrase", category: "Jju frases útiles", spanish: "Venga, le digo.", korean: "알겠어요, 말씀드릴게요.", koreanReading: "algesseoyo malsseumdeurilgeyo", imageCode: "1f4ac" },
  { type: "phrase", category: "Jju frases útiles", spanish: "Quiero hacerte el amor.", korean: "너와 사랑을 나누고 싶어.", koreanReading: "neowa sarangeul nanugo sipeo", imageCode: "2764" },
  { type: "word", category: "Jju números", spanish: "uno", korean: "하나", koreanReading: "hana", imageCode: "31-20e3" },
  { type: "word", category: "Jju números", spanish: "dos", korean: "둘", koreanReading: "dul", imageCode: "32-20e3" },
  { type: "word", category: "Jju números", spanish: "tres", korean: "셋", koreanReading: "set", imageCode: "33-20e3" },
  { type: "word", category: "Jju números", spanish: "cuatro", korean: "넷", koreanReading: "net", imageCode: "34-20e3" },
  { type: "word", category: "Jju números", spanish: "cinco", korean: "다섯", koreanReading: "daseot", imageCode: "35-20e3" },
  { type: "word", category: "Jju números", spanish: "seis", korean: "여섯", koreanReading: "yeoseot", imageCode: "36-20e3" },
  { type: "word", category: "Jju números", spanish: "siete", korean: "일곱", koreanReading: "ilgop", imageCode: "37-20e3" },
  { type: "word", category: "Jju números", spanish: "ocho", korean: "여덟", koreanReading: "yeodeol", imageCode: "38-20e3" },
  { type: "word", category: "Jju números", spanish: "nueve", korean: "아홉", koreanReading: "ahop", imageCode: "39-20e3" },
  { type: "word", category: "Jju números", spanish: "diez", korean: "열", koreanReading: "yeol", imageCode: "1f51f" },
  { type: "word", category: "Jju familia", spanish: "mamá", korean: "엄마", koreanReading: "eomma", imageCode: "1f469" },
  { type: "word", category: "Jju familia", spanish: "papá", korean: "아빠", koreanReading: "appa", imageCode: "1f468" },
  { type: "word", category: "Jju familia", spanish: "abuelo", korean: "할아버지", koreanReading: "harabeoji", imageCode: "1f474" },
  { type: "word", category: "Jju familia", spanish: "abuela", korean: "할머니", koreanReading: "halmeoni", imageCode: "1f475" },
  { type: "word", category: "Jju familia", spanish: "hermano", korean: "형제", koreanReading: "hyeongje", imageCode: "1f466" },
  { type: "word", category: "Jju familia", spanish: "hermana", korean: "자매", koreanReading: "jamae", imageCode: "1f467" },
  { type: "word", category: "Jju familia", spanish: "hijo", korean: "아들", koreanReading: "adeul", imageCode: "1f466" },
  { type: "word", category: "Jju familia", spanish: "hija", korean: "딸", koreanReading: "ttal", imageCode: "1f467" },
  { type: "word", category: "Jju familia", spanish: "primo", korean: "사촌", koreanReading: "sachon", imageCode: "1f9d1" },
  { type: "word", category: "Jju personas", spanish: "hombre", korean: "남자", koreanReading: "namja", imageCode: "1f468" },
  { type: "word", category: "Jju personas", spanish: "mujer", korean: "여자", koreanReading: "yeoja", imageCode: "1f469" },
  { type: "word", category: "Jju personas", spanish: "niño", korean: "아이", koreanReading: "ai", imageCode: "1f9d2" },
  { type: "word", category: "Jju personas", spanish: "bebé", korean: "아기", koreanReading: "agi", imageCode: "1f476" },
  { type: "word", category: "Jju comida", spanish: "manzana", korean: "사과", koreanReading: "sagwa", imageCode: "1f34e" },
  { type: "word", category: "Jju comida", spanish: "piña", korean: "파인애플", koreanReading: "painaepeul", imageCode: "1f34d" },
  { type: "word", category: "Jju comida", spanish: "durazno", korean: "복숭아", koreanReading: "boksunga", imageCode: "1f351" },
  { type: "word", category: "Jju comida", spanish: "sandía", korean: "수박", koreanReading: "subak", imageCode: "1f349" },
  { type: "word", category: "Jju comida", spanish: "plátano", korean: "바나나", koreanReading: "banana", imageCode: "1f34c" },
  { type: "word", category: "Jju comida", spanish: "fresa", korean: "딸기", koreanReading: "ttalgi", imageCode: "1f353" },
  { type: "word", category: "Jju comida", spanish: "pepino", korean: "오이", koreanReading: "oi", imageCode: "1f952" },
  { type: "word", category: "Jju comida", spanish: "pimiento", korean: "피망", koreanReading: "pimang", imageCode: "1fad1" },
  { type: "word", category: "Jju comida", spanish: "zanahoria", korean: "당근", koreanReading: "danggeun", imageCode: "1f955" },
  { type: "word", category: "Jju comida", spanish: "aguacate", korean: "아보카도", koreanReading: "abokado", imageCode: "1f951" },
  { type: "word", category: "Jju comida", spanish: "pera", korean: "배", koreanReading: "bae", imageCode: "1f350" },
  { type: "word", category: "Jju comida", spanish: "ensalada", korean: "샐러드", koreanReading: "saelleodeu", imageCode: "1f957" },
  { type: "word", category: "Jju comida", spanish: "agua", korean: "물", koreanReading: "mul", imageCode: "1f4a7" },
  { type: "word", category: "Jju comida", spanish: "leche", korean: "우유", koreanReading: "uyu", imageCode: "1f95b" },
  { type: "word", category: "Jju comida", spanish: "azúcar", korean: "설탕", koreanReading: "seoltang", imageCode: "1f36c" },
  { type: "word", category: "Jju comida", spanish: "pan", korean: "빵", koreanReading: "ppang", imageCode: "1f35e" },
  { type: "word", category: "Jju comida", spanish: "arroz", korean: "밥", koreanReading: "bap", imageCode: "1f35a" },
  { type: "word", category: "Jju comida", spanish: "pollo", korean: "닭고기", koreanReading: "dakgogi", imageCode: "1f357" },
  { type: "word", category: "Jju comida", spanish: "carne", korean: "고기", koreanReading: "gogi", imageCode: "1f969" },
  { type: "word", category: "Jju comida", spanish: "huevo", korean: "달걀", koreanReading: "dalgyal", imageCode: "1f95a" },
  { type: "word", category: "Jju comida", spanish: "queso", korean: "치즈", koreanReading: "chijeu", imageCode: "1f9c0" },
  { type: "word", category: "Jju comida", spanish: "bebida", korean: "음료", koreanReading: "eumnyo", imageCode: "1f964" },
  { type: "word", category: "Jju comida", spanish: "galleta", korean: "쿠키", koreanReading: "kuki", imageCode: "1f36a" },
  { type: "word", category: "Jju comida", spanish: "pastel", korean: "케이크", koreanReading: "keikeu", imageCode: "1f370" },
  { type: "word", category: "Jju comida", spanish: "batido", korean: "스무디", koreanReading: "seumudi", imageCode: "1f964" },
  { type: "word", category: "Jju comida", spanish: "frijol", korean: "콩", koreanReading: "kong", imageCode: "1fad8" },
  { type: "word", category: "Jju comida", spanish: "verdura", korean: "채소", koreanReading: "chaeso", imageCode: "1f96c" },
  { type: "word", category: "Jju comida", spanish: "postre", korean: "디저트", koreanReading: "dijeoteu", imageCode: "1f36e" },
  { type: "word", category: "Jju comida", spanish: "desayuno", korean: "아침 식사", koreanReading: "achim siksa", imageCode: "1f373" },
  { type: "word", category: "Jju comida", spanish: "almuerzo", korean: "점심 식사", koreanReading: "jeomsim siksa", imageCode: "1f35b" },
  { type: "word", category: "Jju comida", spanish: "cena", korean: "저녁 식사", koreanReading: "jeonyeok siksa", imageCode: "1f37d" },
  { type: "word", category: "Jju tiempo", spanish: "día", korean: "낮 / 하루", koreanReading: "nat / haru", imageCode: "2600" },
  { type: "word", category: "Jju tiempo", spanish: "noche", korean: "밤", koreanReading: "bam", imageCode: "1f319" },
  { type: "word", category: "Jju tiempo", spanish: "tarde", korean: "오후", koreanReading: "ohu", imageCode: "1f31e" },
  { type: "word", category: "Jju tiempo", spanish: "mañana", korean: "아침 / 내일", koreanReading: "achim / naeil", imageCode: "1f305" },
  { type: "word", category: "Jju tiempo", spanish: "ayer", korean: "어제", koreanReading: "eoje", imageCode: "23ea" },
  { type: "word", category: "Jju objetos", spanish: "mesa", korean: "책상 / 테이블", koreanReading: "chaeksang / teibeul", imageCode: "1f6cb" },
  { type: "word", category: "Jju objetos", spanish: "silla", korean: "의자", koreanReading: "uija", imageCode: "1f4ba" },
  { type: "word", category: "Jju animales", spanish: "pescado", korean: "생선", koreanReading: "saengseon", imageCode: "1f41f" },
  { type: "word", category: "Jju animales", spanish: "perro", korean: "개", koreanReading: "gae", imageCode: "1f436" },
  { type: "word", category: "Jju animales", spanish: "gato", korean: "고양이", koreanReading: "goyangi", imageCode: "1f431" },
  { type: "word", category: "Jju ropa", spanish: "camisa", korean: "셔츠", koreanReading: "syeocheu", imageCode: "1f455" },
  { type: "word", category: "Jju ropa", spanish: "vestido", korean: "원피스", koreanReading: "wonpiseu", imageCode: "1f457" },
  { type: "word", category: "Jju ropa", spanish: "abrigo", korean: "코트", koreanReading: "koteu", imageCode: "1f9e5" },
  { type: "word", category: "Jju ropa", spanish: "traje de baño", korean: "수영복", koreanReading: "suyeongbok", imageCode: "1fa71" },
  { type: "word", category: "Jju ropa", spanish: "gorra", korean: "모자", koreanReading: "moja", imageCode: "1f9e2" },
  { type: "word", category: "Jju ropa", spanish: "falda", korean: "치마", koreanReading: "chima", imageCode: "1f45a" },
  { type: "word", category: "Jju ropa", spanish: "chaqueta", korean: "재킷", koreanReading: "jaekit", imageCode: "1f9e5" },
  { type: "word", category: "Jju ropa", spanish: "bufanda", korean: "목도리", koreanReading: "mokdori", imageCode: "1f9e3" },
  { type: "word", category: "Jju ropa", spanish: "cinturón", korean: "벨트", koreanReading: "belteu", imageCode: "1f9e2" },
  { type: "word", category: "Jju ropa", spanish: "collar", korean: "목걸이", koreanReading: "mokgeori", imageCode: "1f4ff" },
  { type: "word", category: "Jju ropa", spanish: "sombrero", korean: "모자", koreanReading: "moja", imageCode: "1f452" },
  { type: "word", category: "Jju objetos", spanish: "cartera", korean: "지갑", koreanReading: "jigap", imageCode: "1f45b" },
  { type: "word", category: "Jju objetos", spanish: "reloj", korean: "시계", koreanReading: "sigye", imageCode: "231a" },
  { type: "word", category: "Jju objetos", spanish: "maleta", korean: "여행 가방", koreanReading: "yeohaeng gabang", imageCode: "1f9f3" },
  { type: "word", category: "Jju objetos", spanish: "cargador", korean: "충전기", koreanReading: "chungjeongi", imageCode: "1f50c" },
  { type: "word", category: "Jju objetos", spanish: "bolsa", korean: "가방", koreanReading: "gabang", imageCode: "1f45c" },
  { type: "word", category: "Jju objetos", spanish: "botella", korean: "병", koreanReading: "byeong", imageCode: "1f37e" },
  { type: "word", category: "Jju lugares", spanish: "libro", korean: "책", koreanReading: "chaek", imageCode: "1f4d6" },
  { type: "word", category: "Jju lugares", spanish: "biblioteca", korean: "도서관", koreanReading: "doseogwan", imageCode: "1f3db" },
  { type: "word", category: "Jju lugares", spanish: "peluquería", korean: "미용실", koreanReading: "miyongsil", imageCode: "1f487" },
  { type: "word", category: "Jju salud", spanish: "medicina", korean: "약", koreanReading: "yak", imageCode: "1f48a" },
  { type: "word", category: "Jju comunicación", spanish: "pregunta", korean: "질문", koreanReading: "jilmun", imageCode: "2753" },
  { type: "word", category: "Jju lugares", spanish: "mercado", korean: "시장", koreanReading: "sijang", imageCode: "1f6d2" },
  { type: "word", category: "Jju lugares", spanish: "edificio", korean: "건물", koreanReading: "geonmul", imageCode: "1f3e2" },
  { type: "word", category: "Jju lugares", spanish: "piso", korean: "층 / 아파트", koreanReading: "cheung / apateu", imageCode: "1f3e2" },
  { type: "word", category: "Jju lugares", spanish: "jardín", korean: "정원", koreanReading: "jeongwon", imageCode: "1fab4" },
  { type: "word", category: "Jju lugares", spanish: "calle", korean: "거리", koreanReading: "geori", imageCode: "1f6e3" },
  { type: "word", category: "Jju lugares", spanish: "discoteca", korean: "클럽", koreanReading: "keulleop", imageCode: "1faa9" },
  { type: "word", category: "Jju lugares", spanish: "lugar", korean: "장소", koreanReading: "jangso", imageCode: "1f4cd" },
  { type: "word", category: "Jju lugares", spanish: "empresa", korean: "회사", koreanReading: "hoesa", imageCode: "1f3e2" },
  { type: "word", category: "Jju naturaleza", spanish: "primavera", korean: "봄", koreanReading: "bom", imageCode: "1f338" },
  { type: "word", category: "Jju naturaleza", spanish: "verano", korean: "여름", koreanReading: "yeoreum", imageCode: "2600" },
  { type: "word", category: "Jju naturaleza", spanish: "otoño", korean: "가을", koreanReading: "gaeul", imageCode: "1f342" },
  { type: "word", category: "Jju naturaleza", spanish: "invierno", korean: "겨울", koreanReading: "gyeoul", imageCode: "2744" },
  { type: "word", category: "Jju naturaleza", spanish: "frío", korean: "추위", koreanReading: "chuwi", imageCode: "2744" },
  { type: "word", category: "Jju naturaleza", spanish: "calor", korean: "더위", koreanReading: "deowi", imageCode: "1f525" },
  { type: "word", category: "Jju naturaleza", spanish: "viento", korean: "바람", koreanReading: "baram", imageCode: "1f32c" },
  { type: "word", category: "Jju naturaleza", spanish: "sol", korean: "해", koreanReading: "hae", imageCode: "2600" },
  { type: "word", category: "Jju naturaleza", spanish: "lluvia", korean: "비", koreanReading: "bi", imageCode: "1f327" },
  { type: "word", category: "Jju entretenimiento", spanish: "película", korean: "영화", koreanReading: "yeonghwa", imageCode: "1f3ac" },
  { type: "word", category: "Jju ubicación", spanish: "detrás", korean: "뒤에", koreanReading: "dwie", imageCode: "1f519" },
  { type: "word", category: "Jju ubicación", spanish: "al lado", korean: "옆에", koreanReading: "yeope", imageCode: "2194" },
  { type: "word", category: "Jju ubicación", spanish: "al frente", korean: "앞쪽에", koreanReading: "apjjoge", imageCode: "2b06" },
  { type: "word", category: "Jju ubicación", spanish: "enfrente de", korean: "앞에", koreanReading: "ape", imageCode: "2b06" },
  { type: "word", category: "Jju ubicación", spanish: "a la izquierda", korean: "왼쪽에", koreanReading: "oenjjoge", imageCode: "2b05" },
  { type: "word", category: "Jju ubicación", spanish: "a la derecha", korean: "오른쪽에", koreanReading: "oreunjjoge", imageCode: "27a1" },
  { type: "word", category: "Jju transporte", spanish: "coche", korean: "자동차", koreanReading: "jadongcha", imageCode: "1f697" },
  { type: "word", category: "Jju personas", spanish: "vecino", korean: "이웃", koreanReading: "iut", imageCode: "1f3d8" },
  { type: "word", category: "Jju estudio", spanish: "colegio", korean: "학교", koreanReading: "hakgyo", imageCode: "1f3eb" },
  { type: "word", category: "Jju estudio", spanish: "lección", korean: "수업", koreanReading: "sueop", imageCode: "1f4d6" },
  { type: "word", category: "Jju estudio", spanish: "curso", korean: "강좌", koreanReading: "gangjwa", imageCode: "1f393" },
  { type: "word", category: "Jju estudio", spanish: "clase", korean: "수업", koreanReading: "sueop", imageCode: "1f3eb" },
  { type: "word", category: "Jju estudio", spanish: "tarea", korean: "숙제", koreanReading: "sukje", imageCode: "270d" },
  { type: "word", category: "Jju estudio", spanish: "ejercicios", korean: "연습 문제", koreanReading: "yeonseup munje", imageCode: "1f4aa" },
  { type: "word", category: "Jju estudio", spanish: "matemáticas", korean: "수학", koreanReading: "suhak", imageCode: "1f522" },
  { type: "word", category: "Jju estudio", spanish: "química", korean: "화학", koreanReading: "hwahak", imageCode: "2697" },
  { type: "word", category: "Jju estudio", spanish: "geografía", korean: "지리", koreanReading: "jiri", imageCode: "1f5fa" },
  { type: "word", category: "Jju estudio", spanish: "literatura", korean: "문학", koreanReading: "munhak", imageCode: "1f4da" },
  { type: "phrase", category: "Jju expresiones", spanish: "al aire libre", korean: "야외에서", koreanReading: "yaoeeseo", imageCode: "1f3d5" },
  { type: "phrase", category: "Jju expresiones", spanish: "en línea", korean: "온라인으로", koreanReading: "onlain-euro", imageCode: "1f4bb" },
  { type: "phrase", category: "Jju expresiones", spanish: "en oferta", korean: "할인 중", koreanReading: "harin jung", imageCode: "1f3f7" },
  { type: "word", category: "Jju compras", spanish: "precio", korean: "가격", koreanReading: "gagyeok", imageCode: "1f4b0" },
  { type: "word", category: "Jju compras", spanish: "caro", korean: "비싼", koreanReading: "bissan", imageCode: "1f4b8" },
  { type: "word", category: "Jju trabajo", spanish: "mesera", korean: "여종업원", koreanReading: "yeojongeobwon", imageCode: "1f469" },
  { type: "word", category: "Jju trabajo", spanish: "jefe", korean: "상사", koreanReading: "sangsa", imageCode: "1f4bc" },
  { type: "word", category: "Jju trabajo", spanish: "abogado", korean: "변호사", koreanReading: "byeonhosa", imageCode: "2696" },
  { type: "word", category: "Jju colores", spanish: "rojo", korean: "빨간색", koreanReading: "ppalgansaek", imageCode: "1f534" },
  { type: "word", category: "Jju colores", spanish: "naranja", korean: "주황색", koreanReading: "juhwangsaek", imageCode: "1f7e0" },
  { type: "word", category: "Jju colores", spanish: "amarillo", korean: "노란색", koreanReading: "noransaek", imageCode: "1f7e1" },
  { type: "word", category: "Jju colores", spanish: "verde", korean: "초록색", koreanReading: "choroksaek", imageCode: "1f7e2" },
  { type: "word", category: "Jju colores", spanish: "azul", korean: "파란색", koreanReading: "paransaek", imageCode: "1f535" },
  { type: "word", category: "Jju colores", spanish: "índigo", korean: "남색", koreanReading: "namsaek", imageCode: "1f537" },
  { type: "word", category: "Jju colores", spanish: "violeta", korean: "보라색", koreanReading: "borasaek", imageCode: "1f7e3" },
  { type: "word", category: "Jju colores", spanish: "morado", korean: "보라색", koreanReading: "borasaek", imageCode: "1f7e3" },
  { type: "word", category: "Jju colores", spanish: "blanco", korean: "흰색", koreanReading: "huinsaek", imageCode: "26aa" },
  { type: "word", category: "Jju colores", spanish: "negro", korean: "검은색", koreanReading: "geomeunsaek", imageCode: "26ab" },
  { type: "word", category: "Jju colores", spanish: "gris", korean: "회색", koreanReading: "hoesaek", imageCode: "26aa" },
  { type: "word", category: "Jju sabor", spanish: "picante", korean: "매운", koreanReading: "maeun", imageCode: "1f336" },
  { type: "word", category: "Jju sabor", spanish: "dulce", korean: "달콤한", koreanReading: "dalkomhan", imageCode: "1f36c" },
  { type: "word", category: "Jju adjetivos", spanish: "bueno", korean: "좋은", koreanReading: "joeun", imageCode: "1f44d" },
  { type: "word", category: "Jju adjetivos", spanish: "malo", korean: "나쁜", koreanReading: "nappeun", imageCode: "1f44e" },
  { type: "word", category: "Jju adjetivos", spanish: "mucho", korean: "많은", koreanReading: "maneun", imageCode: "1f4e6" },
  { type: "word", category: "Jju adjetivos", spanish: "poco", korean: "적은", koreanReading: "jeogeun", imageCode: "1f538" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "con", korean: "함께 / 와", koreanReading: "hamkke / wa", imageCode: "1f91d" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "sin", korean: "없이", koreanReading: "eopsi", imageCode: "1f6ab" },
  { type: "word", category: "Jju adjetivos", spanish: "grande", korean: "큰", koreanReading: "keun", imageCode: "1f418" },
  { type: "word", category: "Jju adjetivos", spanish: "pequeño", korean: "작은", koreanReading: "jageun", imageCode: "1f41c" },
  { type: "word", category: "Jju adjetivos", spanish: "largo", korean: "긴", koreanReading: "gin", imageCode: "1f4cf" },
  { type: "word", category: "Jju adjetivos", spanish: "simpático", korean: "상냥한", koreanReading: "sangnyanghan", imageCode: "1f60a" },
  { type: "word", category: "Jju adjetivos", spanish: "tímido", korean: "수줍은", koreanReading: "sujubeun", imageCode: "1f633" },
  { type: "word", category: "Jju adjetivos", spanish: "serio", korean: "진지한", koreanReading: "jinjihan", imageCode: "1f9d1" },
  { type: "word", category: "Jju adjetivos", spanish: "gracioso", korean: "웃긴", koreanReading: "utgin", imageCode: "1f606" },
  { type: "word", category: "Jju adjetivos", spanish: "divertido", korean: "재미있는", koreanReading: "jaemiinneun", imageCode: "1f389" },
  { type: "word", category: "Jju adjetivos", spanish: "perezoso", korean: "게으른", koreanReading: "geeureun", imageCode: "1f6cc" },
  { type: "word", category: "Jju adjetivos", spanish: "atlético", korean: "운동을 잘하는", koreanReading: "undongeul jalhaneun", imageCode: "1f3c3" },
  { type: "word", category: "Jju adjetivos", spanish: "aburrido", korean: "지루한", koreanReading: "jiruhan", imageCode: "1f971" },
  { type: "word", category: "Jju adjetivos", spanish: "grosero", korean: "무례한", koreanReading: "muryehan", imageCode: "1f620" },
  { type: "word", category: "Jju adjetivos", spanish: "nuevo", korean: "새로운", koreanReading: "saeroun", imageCode: "1f195" },
  { type: "word", category: "Jju adjetivos", spanish: "viejo", korean: "오래된", koreanReading: "oraedoen", imageCode: "1f3da" },
  { type: "word", category: "Jju ubicación", spanish: "lejos", korean: "먼", koreanReading: "meon", imageCode: "1f5fa" },
  { type: "word", category: "Jju ubicación", spanish: "cerca", korean: "가까운", koreanReading: "gakkaun", imageCode: "1f4cd" },
  { type: "phrase", category: "Jju ubicación", spanish: "por aquí", korean: "이 근처에", koreanReading: "i geuncheoe", imageCode: "1f4cd" },
  { type: "word", category: "Jju adjetivos", spanish: "difícil", korean: "어려운", koreanReading: "eoryeoun", imageCode: "1f9e9" },
  { type: "word", category: "Jju adjetivos", spanish: "fácil", korean: "쉬운", koreanReading: "swiun", imageCode: "2705" },
  { type: "word", category: "Jju adjetivos", spanish: "cómodo", korean: "편한", koreanReading: "pyeonhan", imageCode: "1f6cb" },
  { type: "word", category: "Jju compras", spanish: "barato", korean: "싼", koreanReading: "ssan", imageCode: "1f4b5" },
  { type: "word", category: "Jju preguntas", spanish: "¿Qué?", korean: "무엇?", koreanReading: "mueot", imageCode: "2753" },
  { type: "phrase", category: "Jju preguntas", spanish: "¿Qué quieres comer?", korean: "무엇을 먹고 싶어?", koreanReading: "mueoseul meokgo sipeo", imageCode: "1f374" },
  { type: "word", category: "Jju preguntas", spanish: "¿Cuál?", korean: "어느 것?", koreanReading: "eoneu geot", imageCode: "1f500" },
  { type: "phrase", category: "Jju preguntas", spanish: "¿Cuál prefieres?", korean: "어느 것을 더 좋아해?", koreanReading: "eoneu geoseul deo joahae", imageCode: "1f500" },
  { type: "word", category: "Jju preguntas", spanish: "¿Quién?", korean: "누구?", koreanReading: "nugu", imageCode: "1f464" },
  { type: "phrase", category: "Jju preguntas", spanish: "¿Quién llamó?", korean: "누가 전화했어?", koreanReading: "nuga jeonhwahaesseo", imageCode: "1f4de" },
  { type: "word", category: "Jju preguntas", spanish: "¿Dónde?", korean: "어디?", koreanReading: "eodi", imageCode: "1f4cd" },
  { type: "phrase", category: "Jju preguntas", spanish: "¿Dónde vives?", korean: "어디에 살아?", koreanReading: "eodie sara", imageCode: "1f3e0" },
  { type: "word", category: "Jju preguntas", spanish: "¿Cuándo?", korean: "언제?", koreanReading: "eonje", imageCode: "1f4c5" },
  { type: "phrase", category: "Jju preguntas", spanish: "¿Cuándo es la reunión?", korean: "회의가 언제야?", koreanReading: "hoeui-ga eonjeya", imageCode: "1f465" },
  { type: "word", category: "Jju preguntas", spanish: "¿Por qué?", korean: "왜?", koreanReading: "wae", imageCode: "1f914" },
  { type: "phrase", category: "Jju preguntas", spanish: "¿Por qué lloras?", korean: "왜 울어?", koreanReading: "wae ureo", imageCode: "1f62d" },
  { type: "word", category: "Jju preguntas", spanish: "¿Cómo?", korean: "어떻게?", koreanReading: "eotteoke", imageCode: "2699" },
  { type: "phrase", category: "Jju preguntas", spanish: "¿Cómo estás?", korean: "어떻게 지내?", koreanReading: "eotteoke jinae", imageCode: "1f642" },
  { type: "word", category: "Jju preguntas", spanish: "¿Cuánto?", korean: "얼마?", koreanReading: "eolma", imageCode: "1f4b1" },
  { type: "phrase", category: "Jju preguntas", spanish: "¿Cuánto cuesta esto?", korean: "이거 얼마예요?", koreanReading: "igeo eolmayeyo", imageCode: "1f4b0" },
  { type: "word", category: "Jju preguntas", spanish: "¿Cuántos?", korean: "몇 개?", koreanReading: "myeot gae", imageCode: "1f522" },
  { type: "phrase", category: "Jju preguntas", spanish: "¿Cuántos hermanos tienes?", korean: "형제가 몇 명 있어?", koreanReading: "hyeongjega myeot myeong isseo", imageCode: "1f46a" },
  { type: "word", category: "Jju conectores", spanish: "y", korean: "그리고", koreanReading: "geurigo", imageCode: "2795" },
  { type: "word", category: "Jju conectores", spanish: "también", korean: "또한", koreanReading: "ttohan", imageCode: "2795" },
  { type: "word", category: "Jju conectores", spanish: "pero", korean: "하지만", koreanReading: "hajiman", imageCode: "1f501" },
  { type: "word", category: "Jju conectores", spanish: "porque", korean: "왜냐하면", koreanReading: "waenyahamyeon", imageCode: "1f4ac" },
  { type: "word", category: "Jju conectores", spanish: "entonces", korean: "그러면", koreanReading: "geureomyeon", imageCode: "27a1" },
  { type: "phrase", category: "Jju conectores", spanish: "para que", korean: "~하기 위해서", koreanReading: "hagi wihaeseo", imageCode: "1f3af" },
  { type: "word", category: "Jju conectores", spanish: "cuando", korean: "~할 때", koreanReading: "hal ttae", imageCode: "23f0" },
  { type: "phrase", category: "Jju conectores", spanish: "antes de que", korean: "~하기 전에", koreanReading: "hagi jeone", imageCode: "23ee" },
  { type: "word", category: "Jju conectores", spanish: "después", korean: "후에", koreanReading: "hue", imageCode: "23ed" },
  { type: "word", category: "Jju conectores", spanish: "mientras", korean: "~하는 동안", koreanReading: "haneun dongan", imageCode: "23f3" },
  { type: "phrase", category: "Jju conectores", spanish: "al mismo tiempo", korean: "동시에", koreanReading: "dongsie", imageCode: "1f504" },
  { type: "word", category: "Jju conectores", spanish: "como", korean: "~처럼 / 어떻게", koreanReading: "cheoreom / eotteoke", imageCode: "2699" },
  { type: "phrase", category: "Jju conectores", spanish: "por ejemplo", korean: "예를 들어", koreanReading: "yereul deureo", imageCode: "1f4dd" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "de", korean: "~의 / ~에서", koreanReading: "ui / eseo", imageCode: "1f517" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "la", korean: "여성 정관사", koreanReading: "yeoseong jeonggwansa", imageCode: "1f524" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "el", korean: "남성 정관사", koreanReading: "namseong jeonggwansa", imageCode: "1f524" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "que", korean: "~라는 것 / 무엇", koreanReading: "raneun geot / mueot", imageCode: "2753" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "en", korean: "~에", koreanReading: "e", imageCode: "1f4cd" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "a", korean: "~에게 / ~로", koreanReading: "ege / ro", imageCode: "27a1" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "se", korean: "재귀 대명사", koreanReading: "jaegwi daemyeongsa", imageCode: "1f504" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "los", korean: "남성 복수 정관사", koreanReading: "namseong boksu jeonggwansa", imageCode: "1f524" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "por", korean: "~때문에 / ~을 통해", koreanReading: "ttaemune / eul tonghae", imageCode: "1f501" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "una", korean: "하나의", koreanReading: "hanaui", imageCode: "31-20e3" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "su", korean: "그의 / 그녀의", koreanReading: "geuui / geunyeoui", imageCode: "1f9d1" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "no", korean: "아니요 / 아니다", koreanReading: "aniyo / anida", imageCode: "274c" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "lo", korean: "그것을", koreanReading: "geugeoseul", imageCode: "1f449" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "al", korean: "a + el", koreanReading: "a mas el", imageCode: "1f517" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "del", korean: "de + el", koreanReading: "de mas el", imageCode: "1f517" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "sí", korean: "네", koreanReading: "ne", imageCode: "2705" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "pues", korean: "그럼 / 음", koreanReading: "geureom / eum", imageCode: "1f4ac" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "ya", korean: "이미 / 이제", koreanReading: "imi / ije", imageCode: "23f0" },
  { type: "word", category: "Jju palabras pequeñas", spanish: "más", korean: "더", koreanReading: "deo", imageCode: "2795" },
  { type: "phrase", category: "Jju expresiones", spanish: "¿Ya no?", korean: "이제 안 해?", koreanReading: "ije an hae", imageCode: "2753" },
  { type: "phrase", category: "Jju expresiones", spanish: "todos los días", korean: "매일", koreanReading: "maeil", imageCode: "1f4c5" },
  { type: "phrase", category: "Jju expresiones", spanish: "estos días", korean: "요즘", koreanReading: "yojeum", imageCode: "1f4c5" },
  { type: "phrase", category: "Jju expresiones", spanish: "a menudo", korean: "자주", koreanReading: "jaju", imageCode: "1f501" },
  { type: "word", category: "Jju expresiones", spanish: "siempre", korean: "항상", koreanReading: "hangsang", imageCode: "267e" },
  { type: "word", category: "Jju expresiones", spanish: "juntos", korean: "함께", koreanReading: "hamkke", imageCode: "1f91d" },
  { type: "word", category: "Jju cognados", spanish: "animal", korean: "동물", koreanReading: "dongmul", imageCode: "1f981" },
  { type: "word", category: "Jju cognados", spanish: "hospital", korean: "병원", koreanReading: "byeongwon", imageCode: "1f3e5" },
  { type: "word", category: "Jju cognados", spanish: "hotel", korean: "호텔", koreanReading: "hotel", imageCode: "1f3e8" },
  { type: "word", category: "Jju cognados", spanish: "actor", korean: "배우", koreanReading: "baeu", imageCode: "1f3ad" },
  { type: "word", category: "Jju cognados", spanish: "doctor", korean: "의사", koreanReading: "uisa", imageCode: "1f9d1" },
  { type: "word", category: "Jju cognados", spanish: "ideal", korean: "이상적인", koreanReading: "isangjeogin", imageCode: "1f4a1" },
  { type: "word", category: "Jju cognados", spanish: "central", korean: "중앙의", koreanReading: "jungangui", imageCode: "1f3af" },
  { type: "word", category: "Jju cognados", spanish: "final", korean: "마지막", koreanReading: "majimak", imageCode: "1f3c1" },
  { type: "word", category: "Jju cognados", spanish: "total", korean: "전체의", koreanReading: "jeoncheui", imageCode: "1f4af" },
  { type: "word", category: "Jju cognados", spanish: "normal", korean: "보통의", koreanReading: "botongui", imageCode: "1f44c" },
  { type: "word", category: "Jju cognados", spanish: "tropical", korean: "열대의", koreanReading: "yeoldaeeui", imageCode: "1f334" },
  { type: "word", category: "Jju cognados", spanish: "capital", korean: "수도", koreanReading: "sudo", imageCode: "1f3db" },
  { type: "word", category: "Jju cognados", spanish: "familiar", korean: "익숙한 / 가족의", koreanReading: "iksukhan / gajogui", imageCode: "1f46a" },
  { type: "word", category: "Jju cognados", spanish: "manual", korean: "설명서 / 수동의", koreanReading: "seolmyeongseo / sudongui", imageCode: "1f4d8" },
  { type: "word", category: "Jju cognados", spanish: "natural", korean: "자연스러운", koreanReading: "jayeonseureoun", imageCode: "1f333" },
  { type: "word", category: "Jju cognados", spanish: "festival", korean: "축제", koreanReading: "chukje", imageCode: "1f389" },
  { type: "word", category: "Jju cognados", spanish: "popular", korean: "인기 있는", koreanReading: "ingi inneun", imageCode: "2b50" },
  { type: "word", category: "Jju cognados", spanish: "moral", korean: "도덕적인", koreanReading: "dodeokjeogin", imageCode: "2696" },
  { type: "word", category: "Jju cognados", spanish: "original", korean: "원래의", koreanReading: "wollaeeui", imageCode: "1f4a1" },
  { type: "word", category: "Jju cognados", spanish: "material", korean: "재료 / 물질", koreanReading: "jaeryo / muljil", imageCode: "1f9f1" },
  { type: "word", category: "Jju cognados", spanish: "robot", korean: "로봇", koreanReading: "robot", imageCode: "1f916" },
  { type: "word", category: "Jju cognados", spanish: "radio", korean: "라디오", koreanReading: "radio", imageCode: "1f4fb" },
  { type: "word", category: "Jju cognados", spanish: "taxi", korean: "택시", koreanReading: "taeksi", imageCode: "1f695" },
  { type: "word", category: "Jju cognados", spanish: "motor", korean: "모터", koreanReading: "moteo", imageCode: "2699" },
  { type: "word", category: "Jju cognados", spanish: "información", korean: "정보", koreanReading: "jeongbo", imageCode: "2139" },
  { type: "word", category: "Jju cognados", spanish: "música", korean: "음악", koreanReading: "eumak", imageCode: "1f3b5" },
  { type: "word", category: "Jju cognados", spanish: "nación", korean: "국가", koreanReading: "gukga", imageCode: "1f3f3" },
  { type: "word", category: "Jju cognados", spanish: "educación", korean: "교육", koreanReading: "gyoyuk", imageCode: "1f393" },
  { type: "word", category: "Jju cognados", spanish: "familia", korean: "가족", koreanReading: "gajok", imageCode: "1f46a" },
  { type: "word", category: "Jju cognados", spanish: "cultura", korean: "문화", koreanReading: "munhwa", imageCode: "1f3db" },
  { type: "word", category: "Jju cognados", spanish: "presidente", korean: "대통령", koreanReading: "daetongnyeong", imageCode: "1f9d1" },
  { type: "word", category: "Jju cognados", spanish: "color", korean: "색", koreanReading: "saek", imageCode: "1f3a8" },
  { type: "word", category: "Jju cognados", spanish: "universidad", korean: "대학교", koreanReading: "daehakgyo", imageCode: "1f3eb" },
  { type: "word", category: "Jju cognados", spanish: "historia", korean: "역사", koreanReading: "yeoksa", imageCode: "1f4dc" },
  { type: "word", category: "Jju cognados", spanish: "momento", korean: "순간", koreanReading: "sungan", imageCode: "23f1" },
  { type: "word", category: "Jju cognados", spanish: "teléfono", korean: "전화", koreanReading: "jeonhwa", imageCode: "1f4de" },
  { type: "word", category: "Jju cognados", spanish: "restaurante", korean: "식당", koreanReading: "sikdang", imageCode: "1f37d" },
  { type: "word", category: "Jju cognados", spanish: "posible", korean: "가능한", koreanReading: "ganeunghan", imageCode: "2705" },
  { type: "word", category: "Jju cognados", spanish: "importante", korean: "중요한", koreanReading: "jungyohan", imageCode: "2757" },
  { type: "word", category: "Jju cognados", spanish: "diferente", korean: "다른", koreanReading: "dareun", imageCode: "1f500" },
  { type: "word", category: "Jju cognados", spanish: "inteligente", korean: "똑똑한", koreanReading: "ttokttokhan", imageCode: "1f9e0" },
  { type: "word", category: "Jju cognados", spanish: "problema", korean: "문제", koreanReading: "munje", imageCode: "26a0" },
  { type: "word", category: "Jju patrón -ción", spanish: "comunicación", korean: "의사소통", koreanReading: "uisasotong", imageCode: "1f4ac" },
  { type: "word", category: "Jju patrón -ción", spanish: "celebración", korean: "축하", koreanReading: "chukha", imageCode: "1f389" },
  { type: "word", category: "Jju patrón -ción", spanish: "organización", korean: "조직", koreanReading: "jojik", imageCode: "1f5c2" },
  { type: "word", category: "Jju patrón -ción", spanish: "situación", korean: "상황", koreanReading: "sanghwang", imageCode: "1f4cd" },
  { type: "word", category: "Jju patrón -ción", spanish: "relación", korean: "관계", koreanReading: "gwangye", imageCode: "1f91d" },
  { type: "word", category: "Jju patrón -ción", spanish: "presentación", korean: "발표", koreanReading: "balpyo", imageCode: "1f4ca" },
  { type: "word", category: "Jju patrón -ción", spanish: "imaginación", korean: "상상력", koreanReading: "sangsangnyeok", imageCode: "1f4ad" },
  { type: "word", category: "Jju patrón -ción", spanish: "participación", korean: "참여", koreanReading: "chamyeo", imageCode: "1f64b" },
  { type: "word", category: "Jju patrón -ción", spanish: "motivación", korean: "동기", koreanReading: "donggi", imageCode: "1f4aa" },
  { type: "word", category: "Jju patrón -ción", spanish: "identificación", korean: "신분증 / 식별", koreanReading: "sinbunjeung / sikbyeol", imageCode: "1faaa" },
  { type: "word", category: "Jju patrón -ción", spanish: "traducción", korean: "번역", koreanReading: "beonyeok", imageCode: "1f310" },
  { type: "word", category: "Jju patrón -ción", spanish: "creación", korean: "창조", koreanReading: "changjo", imageCode: "1f4a1" },
  { type: "word", category: "Jju patrón -ción", spanish: "revolución", korean: "혁명", koreanReading: "hyeongmyeong", imageCode: "1f504" },
  { type: "word", category: "Jju patrón -ción", spanish: "observación", korean: "관찰", koreanReading: "gwanchal", imageCode: "1f441" },
  { type: "word", category: "Jju patrón -ción", spanish: "decoración", korean: "장식", koreanReading: "jangsik", imageCode: "1f380" },
  { type: "word", category: "Jju patrón -ción", spanish: "conversación", korean: "대화", koreanReading: "daehwa", imageCode: "1f4ac" },
  { type: "word", category: "Jju patrón -ción", spanish: "exploración", korean: "탐험", koreanReading: "tamheom", imageCode: "1f9ed" },
  { type: "word", category: "Jju patrón -idad", spanish: "actividad", korean: "활동", koreanReading: "hwaldong", imageCode: "1f3c3" },
  { type: "word", category: "Jju patrón -idad", spanish: "electricidad", korean: "전기", koreanReading: "jeongi", imageCode: "26a1" },
  { type: "word", category: "Jju patrón -idad", spanish: "productividad", korean: "생산성", koreanReading: "saengsanseong", imageCode: "1f4c8" },
  { type: "word", category: "Jju patrón -idad", spanish: "posibilidad", korean: "가능성", koreanReading: "ganeungseong", imageCode: "2705" },
  { type: "word", category: "Jju patrón -idad", spanish: "responsabilidad", korean: "책임", koreanReading: "chaegim", imageCode: "1f4bc" },
  { type: "word", category: "Jju patrón -idad", spanish: "flexibilidad", korean: "유연성", koreanReading: "yuyeonseong", imageCode: "1f938" },
  { type: "word", category: "Jju patrón -idad", spanish: "estabilidad", korean: "안정성", koreanReading: "anjeongseong", imageCode: "2696" },
  { type: "word", category: "Jju patrón -idad", spanish: "creatividad", korean: "창의성", koreanReading: "changuiseong", imageCode: "1f3a8" },
  { type: "word", category: "Jju patrón -idad", spanish: "curiosidad", korean: "호기심", koreanReading: "hogisim", imageCode: "1f914" },
  { type: "word", category: "Jju patrón -idad", spanish: "humanidad", korean: "인류 / 인간성", koreanReading: "illyu / inganseong", imageCode: "1f465" },
  { type: "word", category: "Jju patrón -idad", spanish: "igualdad", korean: "평등", koreanReading: "pyeongdeung", imageCode: "2696" },
  { type: "word", category: "Jju patrón -idad", spanish: "seguridad", korean: "안전", koreanReading: "anjeon", imageCode: "1f6e1" },
  { type: "word", category: "Jju patrón -idad", spanish: "complejidad", korean: "복잡성", koreanReading: "bokjapseong", imageCode: "1f9e9" },
  { type: "word", category: "Jju patrón -idad", spanish: "realidad", korean: "현실", koreanReading: "hyeonsil", imageCode: "1f441" },
  { type: "word", category: "Jju patrón -idad", spanish: "sensibilidad", korean: "민감성", koreanReading: "mingamseong", imageCode: "1f49f" },
  { type: "word", category: "Jju patrón -idad", spanish: "oportunidad", korean: "기회", koreanReading: "gihoe", imageCode: "1f513" },
  { type: "word", category: "Jju patrón -idad", spanish: "fatalidad", korean: "불운 / 치명성", koreanReading: "burun / chimyeongseong", imageCode: "26a0" },
  { type: "word", category: "Jju patrón -idad", spanish: "generosidad", korean: "관대함", koreanReading: "gwandaeham", imageCode: "1f381" },
  { type: "word", category: "Jju patrón -idad", spanish: "mentalidad", korean: "사고방식", koreanReading: "sagobangsik", imageCode: "1f9e0" },
  { type: "word", category: "Jju patrón -oso", spanish: "famoso", korean: "유명한", koreanReading: "yumyeonghan", imageCode: "2b50" },
  { type: "word", category: "Jju patrón -oso", spanish: "curioso", korean: "호기심 많은", koreanReading: "hogisim maneun", imageCode: "1f914" },
  { type: "word", category: "Jju patrón -oso", spanish: "delicioso", korean: "맛있는", koreanReading: "masinneun", imageCode: "1f60b" },
  { type: "word", category: "Jju patrón -oso", spanish: "ambicioso", korean: "야심 있는", koreanReading: "yasim inneun", imageCode: "1f3af" },
  { type: "word", category: "Jju patrón -oso", spanish: "generoso", korean: "관대한", koreanReading: "gwandaehan", imageCode: "1f381" },
  { type: "word", category: "Jju patrón -oso", spanish: "misterioso", korean: "신비로운", koreanReading: "sinbiroun", imageCode: "1f52e" },
  { type: "word", category: "Jju patrón -oso", spanish: "peligroso", korean: "위험한", koreanReading: "wiheomhan", imageCode: "26a0" },
  { type: "word", category: "Jju patrón -oso", spanish: "glorioso", korean: "영광스러운", koreanReading: "yeonggwangseureoun", imageCode: "1f3c6" },
  { type: "word", category: "Jju patrón -oso", spanish: "religioso", korean: "종교적인", koreanReading: "jonggyojeogin", imageCode: "1f6d0" },
  { type: "word", category: "Jju patrón -oso", spanish: "victorioso", korean: "승리한", koreanReading: "seungnihan", imageCode: "1f3c6" },
  { type: "word", category: "Jju patrón -ico", spanish: "básico", korean: "기본적인", koreanReading: "gibonjeogin", imageCode: "1f4d8" },
  { type: "word", category: "Jju patrón -ico", spanish: "público", korean: "공공의", koreanReading: "gonggongui", imageCode: "1f465" },
  { type: "word", category: "Jju patrón -ico", spanish: "económico", korean: "경제적인", koreanReading: "gyeongjejeogin", imageCode: "1f4b0" },
  { type: "word", category: "Jju patrón -ico", spanish: "histórico", korean: "역사적인", koreanReading: "yeoksajeogin", imageCode: "1f4dc" },
  { type: "word", category: "Jju patrón -ico", spanish: "romántico", korean: "로맨틱한", koreanReading: "romaentikhan", imageCode: "1f498" },
  { type: "word", category: "Jju patrón -ico", spanish: "científico", korean: "과학적인", koreanReading: "gwahakjeogin", imageCode: "1f52c" },
  { type: "word", category: "Jju patrón -ico", spanish: "fantástico", korean: "환상적인", koreanReading: "hwansangjeogin", imageCode: "1f929" },
  { type: "word", category: "Jju patrón -ico", spanish: "mágico", korean: "마법 같은", koreanReading: "mabeop gateun", imageCode: "1fa84" },
  { type: "word", category: "Jju patrón -ico", spanish: "lógico", korean: "논리적인", koreanReading: "nollijeogin", imageCode: "1f9e0" },
  { type: "word", category: "Jju patrón -ico", spanish: "automático", korean: "자동의", koreanReading: "jadongui", imageCode: "2699" },
  { type: "word", category: "Jju patrón -mento", spanish: "argumento", korean: "주장 / 논거", koreanReading: "jujang / nongeo", imageCode: "1f4ac" },
  { type: "word", category: "Jju patrón -mento", spanish: "instrumento", korean: "악기 / 도구", koreanReading: "akki / dogu", imageCode: "1f3b8" },
  { type: "word", category: "Jju patrón -mento", spanish: "documento", korean: "문서", koreanReading: "munseo", imageCode: "1f4c4" },
  { type: "word", category: "Jju patrón -mento", spanish: "apartamento", korean: "아파트", koreanReading: "apateu", imageCode: "1f3e2" },
  { type: "word", category: "Jju patrón -mento", spanish: "movimiento", korean: "움직임", koreanReading: "umjigim", imageCode: "1f3c3" },
  { type: "phrase", category: "Jju frases útiles", spanish: "Hermosa, mi princesa.", korean: "아름다워, 나의 공주님.", koreanReading: "areumdawo naui gongjunim", imageCode: "1f478" },
] satisfies StarterJjuEntry[];

export const starterJjuKoEsCards: VocabularyCard[] = starterJjuKoEsEntries.map(
  (entry, index) => {
    const displayOrder = index + 1;

    return {
      id: getJjuKoEsStarterCardId(displayOrder),
      type: entry.type,
      isStarter: true,
      starterGroup: "jju",
      displayOrder,
      learningMode: "ko_es",
      learningLanguage: "es",
      supportLanguage: "ko",
      learningText: entry.spanish,
      supportText: entry.korean,
      supportReading: entry.koreanReading,
      japaneseRomaji: entry.spanish,
      spanish: entry.spanish,
      category: entry.category,
      imageUrl: getStarterImageUrl(entry.imageCode),
      createdAt: getStarterCreatedAt(displayOrder),
    };
  },
);
