import type { VocabularyCard } from "@/types/card";

export interface StarterJaEsEntry {
  number: number;
  block: string;
  category: string;
  romaji: string;
  spanish: string;
}

export const starterJaEsEntries = [
  { number: 1, block: "A", category: "Identidad personal", romaji: "watashi", spanish: "yo" },
  { number: 2, block: "A", category: "Identidad personal", romaji: "namae", spanish: "nombre" },
  { number: 3, block: "A", category: "Identidad personal", romaji: "nenrei", spanish: "edad" },
  { number: 4, block: "A", category: "Identidad personal", romaji: "hito", spanish: "persona" },
  { number: 5, block: "A", category: "Identidad personal", romaji: "otoko", spanish: "hombre" },
  { number: 6, block: "A", category: "Identidad personal", romaji: "onna", spanish: "mujer" },
  { number: 7, block: "A", category: "Identidad personal", romaji: "kodomo", spanish: "ni?o" },
  { number: 8, block: "A", category: "Identidad personal", romaji: "tomodachi", spanish: "amigo" },
  { number: 9, block: "A", category: "Identidad personal", romaji: "kazoku", spanish: "familia" },
  { number: 10, block: "A", category: "Identidad personal", romaji: "otousan", spanish: "padre" },
  { number: 11, block: "A", category: "Identidad personal", romaji: "okaasan", spanish: "madre" },
  { number: 12, block: "A", category: "Identidad personal", romaji: "ani", spanish: "hermano mayor" },
  { number: 13, block: "A", category: "Identidad personal", romaji: "imouto", spanish: "hermana menor" },
  { number: 14, block: "A", category: "Identidad personal", romaji: "sensei", spanish: "profesor" },
  { number: 15, block: "A", category: "Identidad personal", romaji: "koibito", spanish: "pareja" },
  { number: 16, block: "B", category: "Respuestas inmediatas", romaji: "hai", spanish: "s?" },
  { number: 17, block: "B", category: "Respuestas inmediatas", romaji: "iie", spanish: "no" },
  { number: 18, block: "B", category: "Respuestas inmediatas", romaji: "daijoubu", spanish: "est? bien" },
  { number: 19, block: "B", category: "Respuestas inmediatas", romaji: "dame", spanish: "no se puede" },
  { number: 20, block: "B", category: "Respuestas inmediatas", romaji: "ii", spanish: "bien" },
  { number: 21, block: "B", category: "Respuestas inmediatas", romaji: "sumimasen", spanish: "disculpa" },
  { number: 22, block: "B", category: "Respuestas inmediatas", romaji: "gomen", spanish: "perd?n" },
  { number: 23, block: "B", category: "Respuestas inmediatas", romaji: "onegai", spanish: "por favor" },
  { number: 24, block: "B", category: "Respuestas inmediatas", romaji: "hontou", spanish: "verdad" },
  { number: 25, block: "B", category: "Respuestas inmediatas", romaji: "mochiron", spanish: "claro" },
  { number: 26, block: "B", category: "Respuestas inmediatas", romaji: "tabun", spanish: "tal vez" },
  { number: 27, block: "B", category: "Respuestas inmediatas", romaji: "yokatta", spanish: "qu? bueno" },
  { number: 28, block: "B", category: "Respuestas inmediatas", romaji: "iya", spanish: "no quiero" },
  { number: 29, block: "B", category: "Respuestas inmediatas", romaji: "mate", spanish: "espera" },
  { number: 30, block: "B", category: "Respuestas inmediatas", romaji: "kite", spanish: "ven" },
  { number: 31, block: "C", category: "Entender y hablar", romaji: "wakaru", spanish: "entender" },
  { number: 32, block: "C", category: "Entender y hablar", romaji: "wakaranai", spanish: "no entender" },
  { number: 33, block: "C", category: "Entender y hablar", romaji: "hanasu", spanish: "hablar" },
  { number: 34, block: "C", category: "Entender y hablar", romaji: "kiku", spanish: "escuchar / preguntar" },
  { number: 35, block: "C", category: "Entender y hablar", romaji: "koe", spanish: "voz" },
  { number: 36, block: "C", category: "Entender y hablar", romaji: "oto", spanish: "sonido" },
  { number: 37, block: "C", category: "Entender y hablar", romaji: "hanashi", spanish: "conversaci?n" },
  { number: 38, block: "C", category: "Entender y hablar", romaji: "shitsumon", spanish: "pregunta" },
  { number: 39, block: "C", category: "Entender y hablar", romaji: "kotae", spanish: "respuesta" },
  { number: 40, block: "C", category: "Entender y hablar", romaji: "imi", spanish: "significado" },
  { number: 41, block: "C", category: "Entender y hablar", romaji: "denwa", spanish: "tel?fono" },
  { number: 42, block: "C", category: "Entender y hablar", romaji: "messeeji", spanish: "mensaje" },
  { number: 43, block: "C", category: "Entender y hablar", romaji: "me-ru", spanish: "correo" },
  { number: 44, block: "C", category: "Entender y hablar", romaji: "kotaeru", spanish: "responder" },
  { number: 45, block: "C", category: "Entender y hablar", romaji: "tazuneru", spanish: "preguntar" },
  { number: 46, block: "D", category: "Verbos de vida", romaji: "iku", spanish: "ir" },
  { number: 47, block: "D", category: "Verbos de vida", romaji: "kuru", spanish: "venir" },
  { number: 48, block: "D", category: "Verbos de vida", romaji: "kaeru", spanish: "volver" },
  { number: 49, block: "D", category: "Verbos de vida", romaji: "aruku", spanish: "caminar" },
  { number: 50, block: "D", category: "Verbos de vida", romaji: "hashiru", spanish: "correr" },
  { number: 51, block: "D", category: "Verbos de vida", romaji: "hairu", spanish: "entrar" },
  { number: 52, block: "D", category: "Verbos de vida", romaji: "deru", spanish: "salir" },
  { number: 53, block: "D", category: "Verbos de vida", romaji: "matsu", spanish: "esperar" },
  { number: 54, block: "D", category: "Verbos de vida", romaji: "suru", spanish: "hacer" },
  { number: 55, block: "D", category: "Verbos de vida", romaji: "dekiru", spanish: "poder hacer" },
  { number: 56, block: "D", category: "Verbos de vida", romaji: "dekinai", spanish: "no poder" },
  { number: 57, block: "D", category: "Verbos de vida", romaji: "tsukau", spanish: "usar" },
  { number: 58, block: "D", category: "Verbos de vida", romaji: "erabu", spanish: "elegir" },
  { number: 59, block: "D", category: "Verbos de vida", romaji: "kimaru", spanish: "decidir" },
  { number: 60, block: "D", category: "Verbos de vida", romaji: "ganbatte", spanish: "?nimo" },
  { number: 61, block: "E", category: "Cuerpo y necesidades", romaji: "mizu", spanish: "agua" },
  { number: 62, block: "E", category: "Cuerpo y necesidades", romaji: "gohan", spanish: "comida" },
  { number: 63, block: "E", category: "Cuerpo y necesidades", romaji: "ocha", spanish: "t?" },
  { number: 64, block: "E", category: "Cuerpo y necesidades", romaji: "pan", spanish: "pan" },
  { number: 65, block: "E", category: "Cuerpo y necesidades", romaji: "onaka", spanish: "est?mago" },
  { number: 66, block: "E", category: "Cuerpo y necesidades", romaji: "taberu", spanish: "comer" },
  { number: 67, block: "E", category: "Cuerpo y necesidades", romaji: "nomu", spanish: "beber" },
  { number: 68, block: "E", category: "Cuerpo y necesidades", romaji: "neru", spanish: "dormir" },
  { number: 69, block: "E", category: "Cuerpo y necesidades", romaji: "nemui", spanish: "sue?o" },
  { number: 70, block: "E", category: "Cuerpo y necesidades", romaji: "tsukareta", spanish: "cansado" },
  { number: 71, block: "E", category: "Cuerpo y necesidades", romaji: "atsui", spanish: "calor" },
  { number: 72, block: "E", category: "Cuerpo y necesidades", romaji: "samui", spanish: "fr?o" },
  { number: 73, block: "E", category: "Cuerpo y necesidades", romaji: "byouin", spanish: "hospital" },
  { number: 74, block: "E", category: "Cuerpo y necesidades", romaji: "kusuri", spanish: "medicina" },
  { number: 75, block: "E", category: "Cuerpo y necesidades", romaji: "yasumi", spanish: "descanso" },
  { number: 76, block: "F", category: "Lugares importantes", romaji: "ie", spanish: "casa" },
  { number: 77, block: "F", category: "Lugares importantes", romaji: "eki", spanish: "estaci?n" },
  { number: 78, block: "F", category: "Lugares importantes", romaji: "toire", spanish: "ba?o" },
  { number: 79, block: "F", category: "Lugares importantes", romaji: "mise", spanish: "tienda" },
  { number: 80, block: "F", category: "Lugares importantes", romaji: "resutoran", spanish: "restaurante" },
  { number: 81, block: "F", category: "Lugares importantes", romaji: "gakkou", spanish: "escuela" },
  { number: 82, block: "F", category: "Lugares importantes", romaji: "kaisha", spanish: "empresa" },
  { number: 83, block: "F", category: "Lugares importantes", romaji: "michi", spanish: "camino" },
  { number: 84, block: "F", category: "Lugares importantes", romaji: "machi", spanish: "ciudad" },
  { number: 85, block: "F", category: "Lugares importantes", romaji: "mura", spanish: "pueblo" },
  { number: 86, block: "F", category: "Lugares importantes", romaji: "kuni", spanish: "pa?s" },
  { number: 87, block: "F", category: "Lugares importantes", romaji: "sekai", spanish: "mundo" },
  { number: 88, block: "G", category: "Dinero y compras", romaji: "okane", spanish: "dinero" },
  { number: 89, block: "G", category: "Dinero y compras", romaji: "takai", spanish: "caro" },
  { number: 90, block: "G", category: "Dinero y compras", romaji: "yasui", spanish: "barato" },
  { number: 91, block: "G", category: "Dinero y compras", romaji: "ikura", spanish: "cu?nto" },
  { number: 92, block: "G", category: "Dinero y compras", romaji: "kau", spanish: "comprar" },
  { number: 93, block: "G", category: "Dinero y compras", romaji: "kaado", spanish: "tarjeta" },
  { number: 94, block: "G", category: "Dinero y compras", romaji: "genkin", spanish: "efectivo" },
  { number: 95, block: "G", category: "Dinero y compras", romaji: "receipt", spanish: "recibo" },
  { number: 96, block: "G", category: "Dinero y compras", romaji: "takusan", spanish: "mucho" },
  { number: 97, block: "G", category: "Dinero y compras", romaji: "sukoshi", spanish: "un poco" },
  { number: 98, block: "H", category: "Tiempo", romaji: "kyou", spanish: "hoy" },
  { number: 99, block: "H", category: "Tiempo", romaji: "ashita", spanish: "ma?ana" },
  { number: 100, block: "H", category: "Tiempo", romaji: "kinou", spanish: "ayer" },
  { number: 101, block: "H", category: "Tiempo", romaji: "ima", spanish: "ahora" },
  { number: 102, block: "H", category: "Tiempo", romaji: "ato", spanish: "despu?s" },
  { number: 103, block: "H", category: "Tiempo", romaji: "mae", spanish: "antes" },
  { number: 104, block: "H", category: "Tiempo", romaji: "asa", spanish: "ma?ana temprano" },
  { number: 105, block: "H", category: "Tiempo", romaji: "hiru", spanish: "tarde" },
  { number: 106, block: "H", category: "Tiempo", romaji: "yoru", spanish: "noche" },
  { number: 107, block: "H", category: "Tiempo", romaji: "jikan", spanish: "tiempo" },
  { number: 108, block: "H", category: "Tiempo", romaji: "toki", spanish: "momento" },
  { number: 109, block: "H", category: "Tiempo", romaji: "raishuu", spanish: "pr?xima semana" },
  { number: 110, block: "I", category: "Preguntas poderosas", romaji: "nani", spanish: "qu?" },
  { number: 111, block: "I", category: "Preguntas poderosas", romaji: "dare", spanish: "qui?n" },
  { number: 112, block: "I", category: "Preguntas poderosas", romaji: "doko", spanish: "d?nde" },
  { number: 113, block: "I", category: "Preguntas poderosas", romaji: "itsu", spanish: "cu?ndo" },
  { number: 114, block: "I", category: "Preguntas poderosas", romaji: "naze", spanish: "por qu?" },
  { number: 115, block: "I", category: "Preguntas poderosas", romaji: "dou", spanish: "c?mo" },
  { number: 116, block: "I", category: "Preguntas poderosas", romaji: "dochira", spanish: "cu?l" },
  { number: 117, block: "I", category: "Preguntas poderosas", romaji: "donna", spanish: "qu? tipo" },
  { number: 118, block: "I", category: "Preguntas poderosas", romaji: "ikutsu", spanish: "cu?ntos" },
  { number: 119, block: "I", category: "Preguntas poderosas", romaji: "donna hito", spanish: "qu? tipo de persona" },
  { number: 120, block: "J", category: "Emociones", romaji: "ureshii", spanish: "feliz" },
  { number: 121, block: "J", category: "Emociones", romaji: "sabishii", spanish: "triste" },
  { number: 122, block: "J", category: "Emociones", romaji: "tanoshii", spanish: "divertido" },
  { number: 123, block: "J", category: "Emociones", romaji: "kowai", spanish: "miedo" },
  { number: 124, block: "J", category: "Emociones", romaji: "shinpai", spanish: "preocupaci?n" },
  { number: 125, block: "J", category: "Emociones", romaji: "anshin", spanish: "tranquilidad" },
  { number: 126, block: "J", category: "Emociones", romaji: "komaru", spanish: "problema" },
  { number: 127, block: "J", category: "Emociones", romaji: "okoru", spanish: "enojarse" },
  { number: 128, block: "J", category: "Emociones", romaji: "yorokobu", spanish: "alegrarse" },
  { number: 129, block: "J", category: "Emociones", romaji: "warau", spanish: "re?r" },
  { number: 130, block: "J", category: "Emociones", romaji: "naku", spanish: "llorar" },
  { number: 131, block: "K", category: "Relaciones y afecto", romaji: "ai", spanish: "amor" },
  { number: 132, block: "K", category: "Relaciones y afecto", romaji: "koi", spanish: "enamoramiento" },
  { number: 133, block: "K", category: "Relaciones y afecto", romaji: "deeto", spanish: "cita" },
  { number: 134, block: "K", category: "Relaciones y afecto", romaji: "egao", spanish: "sonrisa" },
  { number: 135, block: "K", category: "Relaciones y afecto", romaji: "kokoro", spanish: "coraz?n" },
  { number: 136, block: "K", category: "Relaciones y afecto", romaji: "kimochi", spanish: "sentimiento" },
  { number: 137, block: "K", category: "Relaciones y afecto", romaji: "shiawase", spanish: "felicidad" },
  { number: 138, block: "K", category: "Relaciones y afecto", romaji: "yume", spanish: "sue?o" },
  { number: 139, block: "K", category: "Relaciones y afecto", romaji: "kibou", spanish: "esperanza" },
  { number: 140, block: "K", category: "Relaciones y afecto", romaji: "yakusoku", spanish: "promesa" },
  { number: 141, block: "K", category: "Relaciones y afecto", romaji: "himitsu", spanish: "secreto" },
  { number: 142, block: "K", category: "Relaciones y afecto", romaji: "aishiteru", spanish: "te amo" },
  { number: 143, block: "L", category: "Gustos y entretenimiento", romaji: "suki", spanish: "gustar" },
  { number: 144, block: "L", category: "Gustos y entretenimiento", romaji: "kirai", spanish: "no gustar" },
  { number: 145, block: "L", category: "Gustos y entretenimiento", romaji: "ongaku", spanish: "m?sica" },
  { number: 146, block: "L", category: "Gustos y entretenimiento", romaji: "uta", spanish: "canci?n" },
  { number: 147, block: "L", category: "Gustos y entretenimiento", romaji: "piano", spanish: "piano" },
  { number: 148, block: "L", category: "Gustos y entretenimiento", romaji: "eiga", spanish: "pel?cula" },
  { number: 149, block: "L", category: "Gustos y entretenimiento", romaji: "hon", spanish: "libro" },
  { number: 150, block: "L", category: "Gustos y entretenimiento", romaji: "shashin", spanish: "foto" },
  { number: 151, block: "L", category: "Gustos y entretenimiento", romaji: "odoru", spanish: "bailar" },
  { number: 152, block: "L", category: "Gustos y entretenimiento", romaji: "asobu", spanish: "jugar" },
  { number: 153, block: "L", category: "Gustos y entretenimiento", romaji: "ryokou", spanish: "viaje" },
  { number: 154, block: "M", category: "Trabajo y estudio", romaji: "shigoto", spanish: "trabajo" },
  { number: 155, block: "M", category: "Trabajo y estudio", romaji: "kaigi", spanish: "reuni?n" },
  { number: 156, block: "M", category: "Trabajo y estudio", romaji: "mondai", spanish: "problema" },
  { number: 157, block: "M", category: "Trabajo y estudio", romaji: "keiken", spanish: "experiencia" },
  { number: 158, block: "M", category: "Trabajo y estudio", romaji: "chance", spanish: "oportunidad" },
  { number: 159, block: "M", category: "Trabajo y estudio", romaji: "seikou", spanish: "?xito" },
  { number: 160, block: "M", category: "Trabajo y estudio", romaji: "shippai", spanish: "fracaso" },
  { number: 161, block: "M", category: "Trabajo y estudio", romaji: "benkyou", spanish: "estudio" },
  { number: 162, block: "M", category: "Trabajo y estudio", romaji: "narau", spanish: "aprender" },
  { number: 163, block: "M", category: "Trabajo y estudio", romaji: "oshieru", spanish: "ense?ar" },
  { number: 164, block: "M", category: "Trabajo y estudio", romaji: "renshuu", spanish: "pr?ctica" },
  { number: 165, block: "M", category: "Trabajo y estudio", romaji: "jouzu", spanish: "h?bil" },
  { number: 166, block: "N", category: "Adjetivos clave (1)", romaji: "kirei", spanish: "bonito" },
  { number: 167, block: "N", category: "Adjetivos clave (1)", romaji: "kawaii", spanish: "lindo" },
  { number: 168, block: "N", category: "Adjetivos clave (1)", romaji: "kakkoii", spanish: "atractivo" },
  { number: 169, block: "N", category: "Adjetivos clave (1)", romaji: "suteki", spanish: "encantador" },
  { number: 170, block: "N", category: "Adjetivos clave (1)", romaji: "ookii", spanish: "grande" },
  { number: 171, block: "N", category: "Adjetivos clave (1)", romaji: "chiisai", spanish: "peque?o" },
  { number: 172, block: "N", category: "Adjetivos clave (1)", romaji: "atarashii", spanish: "nuevo" },
  { number: 173, block: "N", category: "Adjetivos clave (1)", romaji: "furui", spanish: "viejo" },
  { number: 174, block: "N", category: "Adjetivos clave (1)", romaji: "muzukashii", spanish: "dif?cil" },
  { number: 175, block: "N", category: "Adjetivos clave (1)", romaji: "kantan", spanish: "f?cil" },
  { number: 176, block: "N", category: "Adjetivos clave (1)", romaji: "sugoi", spanish: "incre?ble" },
  { number: 177, block: "N", category: "Adjetivos clave (1)", romaji: "benri", spanish: "conveniente" },
  { number: 178, block: "N", category: "Adjetivos clave (1)", romaji: "taihen", spanish: "complicado" },
  { number: 179, block: "N", category: "Adjetivos clave (1)", romaji: "hen", spanish: "raro" },
  { number: 180, block: "N", category: "Adjetivos clave (1)", romaji: "akarui", spanish: "alegre / brillante" },
  { number: 181, block: "N", category: "Adjetivos clave (1)", romaji: "kurai", spanish: "oscuro / triste" },
  { number: 182, block: "N", category: "Adjetivos clave (1)", romaji: "shizuka", spanish: "tranquilo" },
  { number: 183, block: "N", category: "Adjetivos clave (1)", romaji: "urusai", spanish: "ruidoso" },
  { number: 184, block: "N", category: "Adjetivos clave (1)", romaji: "nigiyaka", spanish: "animado" },
  { number: 185, block: "N", category: "Adjetivos clave (1)", romaji: "omoi", spanish: "pesado" },
  { number: 186, block: "N", category: "Adjetivos clave (1)", romaji: "karui", spanish: "ligero" },
  { number: 187, block: "N", category: "Adjetivos clave (1)", romaji: "nagai", spanish: "largo" },
  { number: 188, block: "N", category: "Adjetivos clave (1)", romaji: "mijikai", spanish: "corto" },
  { number: 189, block: "N", category: "Adjetivos clave (1)", romaji: "anzen", spanish: "seguro" },
  { number: 190, block: "N", category: "Adjetivos clave (1)", romaji: "abunai", spanish: "peligroso" },
  { number: 191, block: "N", category: "Adjetivos clave (1)", romaji: "majime", spanish: "serio" },
  { number: 192, block: "N", category: "Adjetivos clave (1)", romaji: "yasashii", spanish: "amable" },
  { number: 193, block: "N", category: "Adjetivos clave (1)", romaji: "shinsetsu", spanish: "gentil" },
  { number: 194, block: "N", category: "Adjetivos clave (1)", romaji: "kibishii", spanish: "estricto" },
  { number: 195, block: "N", category: "Adjetivos clave (1)", romaji: "tokubetsu", spanish: "especial" },
  { number: 196, block: "N", category: "Adjetivos clave (1)", romaji: "taisetsu", spanish: "importante" },
  { number: 197, block: "N", category: "Adjetivos clave (1)", romaji: "utsukushii", spanish: "hermoso" },
  { number: 198, block: "O", category: "Naturaleza y mundo", romaji: "yama", spanish: "monta?a" },
  { number: 199, block: "O", category: "Naturaleza y mundo", romaji: "umi", spanish: "mar" },
  { number: 200, block: "O", category: "Naturaleza y mundo", romaji: "sora", spanish: "cielo" },
  { number: 201, block: "O", category: "Naturaleza y mundo", romaji: "ame", spanish: "lluvia" },
  { number: 202, block: "O", category: "Naturaleza y mundo", romaji: "taiyou", spanish: "sol" },
  { number: 203, block: "O", category: "Naturaleza y mundo", romaji: "tsuki", spanish: "luna" },
  { number: 204, block: "O", category: "Naturaleza y mundo", romaji: "hoshi", spanish: "estrella" },
  { number: 205, block: "O", category: "Naturaleza y mundo", romaji: "kaze", spanish: "viento" },
  { number: 206, block: "O", category: "Naturaleza y mundo", romaji: "hana", spanish: "flor" },
  { number: 207, block: "O", category: "Naturaleza y mundo", romaji: "ki", spanish: "?rbol" },
  { number: 208, block: "O", category: "Naturaleza y mundo", romaji: "hi", spanish: "fuego" },
  { number: 209, block: "O", category: "Naturaleza y mundo", romaji: "tsuchi", spanish: "tierra" },
  { number: 210, block: "P", category: "Animales", romaji: "inu", spanish: "perro" },
  { number: 211, block: "P", category: "Animales", romaji: "neko", spanish: "gato" },
  { number: 212, block: "P", category: "Animales", romaji: "tori", spanish: "p?jaro" },
  { number: 213, block: "P", category: "Animales", romaji: "sakana", spanish: "pez" },
  { number: 214, block: "P", category: "Animales", romaji: "uma", spanish: "caballo" },
  { number: 215, block: "P", category: "Animales", romaji: "usagi", spanish: "conejo" },
  { number: 216, block: "Q", category: "Movimiento social", romaji: "au", spanish: "encontrarse" },
  { number: 217, block: "Q", category: "Movimiento social", romaji: "wakareru", spanish: "separarse" },
  { number: 218, block: "Q", category: "Movimiento social", romaji: "ageru", spanish: "dar" },
  { number: 219, block: "Q", category: "Movimiento social", romaji: "morau", spanish: "recibir" },
  { number: 220, block: "Q", category: "Movimiento social", romaji: "kureru", spanish: "darme" },
  { number: 221, block: "Q", category: "Movimiento social", romaji: "ikou", spanish: "vamos" },
  { number: 222, block: "Q", category: "Movimiento social", romaji: "kaette", spanish: "vuelve" },
  { number: 223, block: "Q", category: "Movimiento social", romaji: "aitai", spanish: "quiero verte" },
  { number: 224, block: "Q", category: "Movimiento social", romaji: "shinjiru", spanish: "confiar" },
  { number: 225, block: "Q", category: "Movimiento social", romaji: "tasukaru", spanish: "recibir ayuda" },
  { number: 226, block: "R", category: "Expresiones frecuentes", romaji: "zettai", spanish: "definitivamente" },
  { number: 227, block: "R", category: "Expresiones frecuentes", romaji: "mada", spanish: "todav?a" },
  { number: 228, block: "R", category: "Expresiones frecuentes", romaji: "mou", spanish: "ya" },
  { number: 229, block: "R", category: "Expresiones frecuentes", romaji: "zenzen", spanish: "para nada" },
  { number: 230, block: "R", category: "Expresiones frecuentes", romaji: "itsumo", spanish: "siempre" },
  { number: 231, block: "R", category: "Expresiones frecuentes", romaji: "tokidoki", spanish: "a veces" },
  { number: 232, block: "R", category: "Expresiones frecuentes", romaji: "amari", spanish: "no mucho" },
  { number: 233, block: "R", category: "Expresiones frecuentes", romaji: "zenbu", spanish: "todo" },
  { number: 234, block: "R", category: "Expresiones frecuentes", romaji: "minna", spanish: "todos" },
  { number: 235, block: "R", category: "Expresiones frecuentes", romaji: "kondo", spanish: "pr?xima vez" },
  { number: 236, block: "R", category: "Expresiones frecuentes", romaji: "saigo", spanish: "final" },
  { number: 237, block: "R", category: "Expresiones frecuentes", romaji: "hajime", spanish: "comienzo" },
  { number: 238, block: "S", category: "Vida social", romaji: "hima", spanish: "tiempo libre" },
  { number: 239, block: "S", category: "Vida social", romaji: "kyuujitsu", spanish: "d?a libre" },
  { number: 240, block: "S", category: "Vida social", romaji: "shuumatsu", spanish: "fin de semana" },
  { number: 241, block: "S", category: "Vida social", romaji: "tanjoubi", spanish: "cumplea?os" },
  { number: 242, block: "S", category: "Vida social", romaji: "omatsuri", spanish: "festival" },
  { number: 243, block: "S", category: "Vida social", romaji: "paatii", spanish: "fiesta" },
  { number: 244, block: "S", category: "Vida social", romaji: "konban", spanish: "esta noche" },
  { number: 245, block: "S", category: "Vida social", romaji: "kesa", spanish: "esta ma?ana" },
  { number: 246, block: "S", category: "Vida social", romaji: "mayoi", spanish: "perdido" },
  { number: 247, block: "S", category: "Vida social", romaji: "denwa", spanish: "llamada" },
  { number: 248, block: "T", category: "Acciones extra", romaji: "miru", spanish: "ver" },
  { number: 249, block: "T", category: "Acciones extra", romaji: "yomu", spanish: "leer" },
  { number: 250, block: "T", category: "Acciones extra", romaji: "noru", spanish: "subir / montar" },
  { number: 251, block: "T", category: "Acciones extra", romaji: "oriru", spanish: "bajar" },
  { number: 252, block: "T", category: "Acciones extra", romaji: "okiru", spanish: "despertar" },
  { number: 253, block: "T", category: "Acciones extra", romaji: "nareru", spanish: "acostumbrarse" },
  { number: 254, block: "T", category: "Acciones extra", romaji: "hajimaru", spanish: "empezar" },
  { number: 255, block: "T", category: "Acciones extra", romaji: "owaru", spanish: "terminar" },
  { number: 256, block: "T", category: "Acciones extra", romaji: "tsuzuku", spanish: "continuar" },
  { number: 257, block: "T", category: "Acciones extra", romaji: "yoroshiku", spanish: "buen trato / encantado" },
  { number: 258, block: "U", category: "Transporte y movimiento", romaji: "densha", spanish: "tren" },
  { number: 259, block: "U", category: "Transporte y movimiento", romaji: "basu", spanish: "bus" },
  { number: 260, block: "U", category: "Transporte y movimiento", romaji: "kuruma", spanish: "carro" },
  { number: 261, block: "U", category: "Transporte y movimiento", romaji: "jitensha", spanish: "bicicleta" },
  { number: 262, block: "U", category: "Transporte y movimiento", romaji: "hikouki", spanish: "avi?n" },
  { number: 263, block: "U", category: "Transporte y movimiento", romaji: "taxi", spanish: "taxi" },
  { number: 264, block: "U", category: "Transporte y movimiento", romaji: "michi", spanish: "calle / camino" },
  { number: 265, block: "U", category: "Transporte y movimiento", romaji: "chikaku", spanish: "cerca" },
  { number: 266, block: "U", category: "Transporte y movimiento", romaji: "tooi", spanish: "lejos" },
  { number: 267, block: "U", category: "Transporte y movimiento", romaji: "hayai", spanish: "r?pido / temprano" },
  { number: 268, block: "U", category: "Transporte y movimiento", romaji: "osoi", spanish: "lento / tarde" },
  { number: 269, block: "V", category: "Casa y objetos diarios", romaji: "kaban", spanish: "bolso" },
  { number: 270, block: "V", category: "Casa y objetos diarios", romaji: "kagi", spanish: "llave" },
  { number: 271, block: "V", category: "Casa y objetos diarios", romaji: "kasa", spanish: "paraguas" },
  { number: 272, block: "V", category: "Casa y objetos diarios", romaji: "kutsu", spanish: "zapatos" },
  { number: 273, block: "V", category: "Casa y objetos diarios", romaji: "fuku", spanish: "ropa" },
  { number: 274, block: "V", category: "Casa y objetos diarios", romaji: "isu", spanish: "silla" },
  { number: 275, block: "V", category: "Casa y objetos diarios", romaji: "tsukue", spanish: "mesa / escritorio" },
  { number: 276, block: "V", category: "Casa y objetos diarios", romaji: "doa", spanish: "puerta" },
  { number: 277, block: "V", category: "Casa y objetos diarios", romaji: "mado", spanish: "ventana" },
  { number: 278, block: "V", category: "Casa y objetos diarios", romaji: "heya", spanish: "habitaci?n" },
  { number: 279, block: "W", category: "Tecnolog?a y vida moderna", romaji: "wi-fi", spanish: "wifi" },
  { number: 280, block: "W", category: "Tecnolog?a y vida moderna", romaji: "pasokon", spanish: "computador" },
  { number: 281, block: "W", category: "Tecnolog?a y vida moderna", romaji: "apuri", spanish: "aplicaci?n" },
  { number: 282, block: "W", category: "Tecnolog?a y vida moderna", romaji: "kamera", spanish: "c?mara" },
  { number: 283, block: "W", category: "Tecnolog?a y vida moderna", romaji: "terebi", spanish: "televisi?n" },
  { number: 284, block: "W", category: "Tecnolog?a y vida moderna", romaji: "rajio", spanish: "radio" },
  { number: 285, block: "W", category: "Tecnolog?a y vida moderna", romaji: "denchi", spanish: "bater?a" },
  { number: 286, block: "W", category: "Tecnolog?a y vida moderna", romaji: "juuden", spanish: "cargar bater?a" },
  { number: 287, block: "X", category: "Salud y emergencia", romaji: "itai", spanish: "dolor" },
  { number: 288, block: "X", category: "Salud y emergencia", romaji: "daijoubu", spanish: "estar bien" },
  { number: 289, block: "X", category: "Salud y emergencia", romaji: "kusuri", spanish: "medicina" },
  { number: 290, block: "X", category: "Salud y emergencia", romaji: "byouki", spanish: "enfermedad" },
  { number: 291, block: "X", category: "Salud y emergencia", romaji: "jiko", spanish: "accidente" },
  { number: 292, block: "X", category: "Salud y emergencia", romaji: "keisatsu", spanish: "polic?a" },
  { number: 293, block: "X", category: "Salud y emergencia", romaji: "tasukete", spanish: "ay?dame" },
  { number: 294, block: "X", category: "Salud y emergencia", romaji: "abunai", spanish: "peligroso" },
  { number: 295, block: "X", category: "Salud y emergencia", romaji: "anzen", spanish: "seguro" },
  { number: 296, block: "Y", category: "Fuerza interior", romaji: "jiyuu", spanish: "libertad" },
  { number: 297, block: "Y", category: "Fuerza interior", romaji: "chikara", spanish: "fuerza" },
  { number: 298, block: "Y", category: "Fuerza interior", romaji: "yuuki", spanish: "valent?a" },
  { number: 299, block: "Y", category: "Fuerza interior", romaji: "genjitsu", spanish: "realidad" },
  { number: 300, block: "Y", category: "Fuerza interior", romaji: "mirai", spanish: "futuro" },
] satisfies StarterJaEsEntry[];

function getStarterCardId(number: number): string {
  return `00000000-0000-4000-8000-${String(number).padStart(12, "0")}`;
}

function getCreatedAt(number: number): string {
  return new Date(Date.UTC(2026, 0, 1, 0, 0, number)).toISOString();
}

export const starterJaEsCards: VocabularyCard[] = starterJaEsEntries.map((entry) => ({
  id: getStarterCardId(entry.number),
  type: "word",
  isStarter: true,
  learningMode: "ja_es",
  learningLanguage: "ja",
  supportLanguage: "es",
  learningText: entry.romaji,
  supportText: entry.spanish,
  japaneseRomaji: entry.romaji,
  spanish: entry.spanish,
  category: `Bloque ${entry.block} - ${entry.category}`,
  createdAt: getCreatedAt(entry.number),
}));
